### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Addonman** [sylvanaar/prat-3-0#10]
Message: ..\FrameXML\ChatConfigFrame.lua line 1462:
   attempt to index local 'info' (a nil value)
Debug:
   [C]: ?
   ..\FrameXML\ChatConfigFrame.lua:1462: GetMessageTypeColor()
   Prat-3.0\modules\Editbox.lua:560:
      Prat-3.0\modules\Editbox.lua:549
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:4095: ChatEdit_ResetChatType()
   ..\FrameXML\ChatFrame.lua:4076: ChatEdit_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ..\FrameXML\ChatFrame.lua:4134:
      ..\FrameXML\ChatFrame.lua:4122
   [C]: ?
   [C]: ChatEdit_ActivateChat()
   ..\FrameXML\ChatFrame.lua:3755:
      ..\FrameXML\ChatFrame.lua:3744
   [C]: ChatFrame_OpenChat()
   [string "OPENCHAT"]:1:
      [string "OPENCHAT"]:1
Locals:

**Comment by sylvanaar** [comment]
Retail or Classic?

**Comment by sylvanaar** [comment]
Related maybe: #6

**Comment by Addonman** [comment]
Retail

**Comment by sylvanaar** [comment]
This only happens to certain users, and never me - so I am at a loss - there must be some combination of settings or a certain locale, or something.....

**Comment by Addonman** [comment]
I started to happen like month or two ago.Not sure what happened during that time since lots of addon changes were as well in that time.  Cant say for 100% but it seems its resulting in chat box always being  visible and also i noticed that it breaks trying to right click on char and /w someone.If you try to /w you only get say chanell.(using wim as well as addon). Not sure if i means anything for this bug ,but i happens when you press enter to open up chat and say something.

**Comment by sylvanaar** [comment]
I can right-click and whisper people and I am using WIM too!

My chatframe is always visible - are you saying the editbox is always visible?

Please post your prat saved variables and a list of your addons.

**Comment by Addonman** [comment]
Prat3DB = {
	["namespaces"] = {
		["Prat_TellTarget"] = {
		},
		["Prat_AltNames"] = {
			["profiles"] = {
				["Default"] = {
					["pncol"] = false,
				},
			},
		},
		["Prat_PlayerNames"] = {
			["profiles"] = {
				["Default"] = {
					["showtargeticon"] = true,
				},
			},
		},
		["Prat_Frames"] = {
			["profiles"] = {
				["Default"] = {
					["minchatwidthdefault"] = 296,
					["maxchatheightdefault"] = 400,
					["maxchatwidthdefault"] = 608.0000610351563,
					["initialized"] = true,
				},
			},
		},
		["Prat_ChannelColorMemory"] = {
			["profiles"] = {
				["Default"] = {
					["colors"] = {
						["community:114505412:1"] = {
							["r"] = 0.509803950786591,
							["g"] = 0.772549092769623,
							["b"] = 1,
						},
						["general"] = {
							["r"] = 1,
							["g"] = 0.7529412508010864,
							["b"] = 0.7529412508010864,
						},
						["localdefense"] = {
							["r"] = 1,
							["g"] = 0.752941250801086,
							["b"] = 0.752941250801086,
						},
						["community:115910812:1"] = {
							["b"] = 0.752941250801086,
							["g"] = 0.752941250801086,
							["r"] = 1,
						},
						["community:115805962:1"] = {
							["r"] = 1,
							["g"] = 0.752941250801086,
							["b"] = 0.752941250801086,
						},
					},
				},
			},
		},
		["Prat_Editbox"] = {
		},
		["Prat_Fading"] = {
		},
		["Prat_UrlCopy"] = {
		},
		["Prat_History"] = {
		},
		["Prat_Font"] = {
			["profiles"] = {
				["Default"] = {
					["size"] = {
						["ChatFrame2"] = 14,
						["ChatFrame1"] = 14,
					},
				},
			},
		},
		["Prat_ChannelNames"] = {
		},
		["Prat_KeyBindings"] = {
		},
		["Prat_Bubbles"] = {
		},
		["Prat_Scroll"] = {
		},
		["Prat_Timestamps"] = {
			["profiles"] = {
				["Default"] = {
					["timestampcolor"] = {
						["r"] = 0.937254901960784,
						["g"] = 0.937254901960784,
						["b"] = 0.937254901960784,
					},
				},
			},
		},
		["Prat_Achievements"] = {
			["profiles"] = {
				["Default"] = {
					["showGratsLink"] = true,
					["customGrats"] = false,
				},
			},
		},
		["Prat_Paragraph"] = {
		},
		["Prat_Alias"] = {
		},
		["Prat_OriginalButtons"] = {
		},
		["Prat_Highlight"] = {
		},
		["Prat_ChannelSticky"] = {
		},
		["Prat_Sounds"] = {
		},
		["Prat_Invites"] = {
		},
		["Prat_PopupMessage"] = {
		},
		["Prat_CopyChat"] = {
		},
		["Prat_ChatLog"] = {
		},
		["Prat_Search"] = {
		},
		["Prat_Buttons"] = {
		},
		["Prat_ServerNames"] = {
		},
		["Prat_HoverTips"] = {
		},
	},
	["profileKeys"] = {
		["Airlock - Xavius"] = "Default",
		["Airmago - Twisting Nether"] = "Default",
		["Guesswhois - Silvermoon"] = "Default",
		["Airmonk - Xavius"] = "Default",
		["Testmonkster - Draenor"] = "Default",
		["Airkiller - Twisting Nether"] = "Default",
		["Discomonster - Silvermoon"] = "Default",
		["Testmonk - Silvermoon"] = "Default",
		["Airbear - Twisting Nether"] = "Default",
		["Airlocko - Twisting Nether"] = "Default",
		["Airdruid - Xavius"] = "Default",
		["Airofcro - Xavius"] = "Default",
		["Airdeathk - Silvermoon"] = "Default",
		["Airmonk - Twisting Nether"] = "Default",
		["Airsham - Twisting Nether"] = "Default",
		["Airdoc - Xavius"] = "Default",
		["Guesswhois - Xavius"] = "Default",
		["Airwarr - Silvermoon"] = "Default",
		["Airsham - Xavius"] = "Default",
		["Airpala - Xavius"] = "Default",
		["Airdh - Silvermoon"] = "Default",
		["Airdh - Twisting Nether"] = "Default",
		["Aircro - Silvermoon"] = "Default",
		["Airpala - Twisting Nether"] = "Default",
		["Airkiller - Xavius"] = "Default",
		["Airdk - Ravencrest"] = "Default",
		["Airhunt - Twisting Nether"] = "Default",
		["Airofcro - Twisting Nether"] = "Default",
		["Airdk - Twisting Nether"] = "Default",
		["Airmonk - Silvermoon"] = "Default",
		["Airhunt - Xavius"] = "Default",
		["Airdoc - Twisting Nether"] = "Default",
		["Airmage - Xavius"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["modules"] = {
				["ChatLog"] = 2,
				["PopupMessage"] = 2,
				["AltNames"] = 2,
				["Sounds"] = 2,
				["Paragraph"] = 2,
				["KeyBindings"] = 2,
				["OriginalButtons"] = 2,
				["Alias"] = 2,
			},
		},
	},
}

**Comment by sylvanaar** [comment]
Untried:

> Actually, i randomly discovered a hotfix.    1. Go to Prat -> Display Settings, untick ALL sticky channels. 2. Realod UI 3. Enable the channels you want.   /Calth

**Comment by Addonman** [comment]
Tried working .If you try doing this and reloging not working,but if you just /reload then it works.only bad thing is that you need to do on every char separtly even do i use only default profile on all chars.

**Comment by Movix** [comment]
Hello,

i noticed that when using filters and choosing as output a channel and having the option "output message only"  unchecked this error occurs and no message is posted  (tested  with guild  channel). When checking the option "output message only" no more error and  post happens  as expected ini the  guild channel.
It seems to me as if the data for sendMessage() holds  some invalid/unallowed strings in the channel name /  player name  that  is supposed to be shown, perhaps some formatting escaped sequences.

Thank you for this addon, used it years ago, and i'm happy you made a classic version.

I use the filter module to parse instance names in LFG so thatt i get an alert and ini some situations i output to the guild channel. It would be  a great addition if i could define serveral strings to look for  within one filter. If i want  to be notified  for Molten Core in the current release, ii have to defiinie  multiple filters to look for "MC, mc, molten core, Molten Core, MOLTEN CORE" to be sure to catch most of the wanted posts.

**Comment by Addonman** [comment]
I just noticed it doenst stay fixed.Yesterday i was on  char i was thinking i fixed it for sure but i just now logged on that char and i get same bug message.

**Comment by Addonman** [comment]
Did little more testing.On warr fix isnt permenent but on druid seems it was more permenent adn its weird,Diff in addons is like decursive and nugcombobar which shouldnt cause this diff.

**Comment by Addonman** [comment]
Said it too soon.Another relog and bug is back on druid as well.

**Comment by Addonman** [comment]
@sylvanaar Found perhaps more permanent solution for this problem?

**Comment by Addonman** [comment]
Are you sure this fixes this bug? I was looking to change code myself  and try it myself but seems this code  isnt intendeed for line 870 of module/player name.

**Comment by Addonman** [comment]
> Are you sure this fixes this bug? I was looking to change code myself and try it myself but seems this code isnt intendeed for line 870 of module/player name.

Even tried to put it somewhere else like around line 1519 but still same bug.

**Comment by Addonman** [comment]
Any progress on this bug?

**Comment by Addonman** [comment]
Any fix with 8.3 for this?

**Comment by sylvanaar** [comment]
I believe I see the issue @Addonman 

In editbox.lua:560

```
          local r, g, b = GetMessageTypeColor("CHANNEL" .. chan)
```

should be

```
         local r, g, b = GetMessageTypeColor("CHAT_MSG_CHANNEL" .. chan)
```

I'm just speculating - but I am about to start testing.

I will be pushing this change any minute as it seems to work for me. Please confirm if it fixes your issue and I will keep or rollback


TO HELP DEBUG:

Add this code:
`print(chan)`

before

`          local r, g, b = GetMessageTypeColor("CHANNEL" .. chan)`

**Comment by Addonman** [comment]
Ok.Going to try that.

**Comment by sylvanaar** [comment]
@Addonman  are you on IRC or Discord?

**Comment by Addonman** [comment]
have discord

**Comment by sylvanaar** [comment]
@Addonman sylvaan#8656

**Comment by Addonman** [comment]
I hope .Fixed. 10x  to Sylvanaar.
