### ISSUE TITLE
tabs sometimes reappear

### ISSUE THREAD

**Issue by Aur0r4** [sylvanaar/prat-3-0#100]
Hi sylvanaar,

i have configured Prat to hide chat tabs, however some tabs (often the general tab, but sometimes also a whisper tab) are shown sporadically.

These are my default tabs:
![image](https://user-images.githubusercontent.com/28149249/84573738-c59e1400-ada2-11ea-8476-a3fdd51fdc58.png)

This is what it usually looks like (tabs hidden):

![image](https://user-images.githubusercontent.com/28149249/84573753-d5b5f380-ada2-11ea-80c5-cc4bbe53644b.png)

This is what it looks like when the tab reappears:
![image](https://user-images.githubusercontent.com/28149249/84573775-f3835880-ada2-11ea-8de3-24d11eb030c0.png)

If you move the mouse over the tab for a short time, it disappears again.

Is this a bug or a wanted feature? I first noticed it at the beginning of WoW-Classic, when I installed Prat Classic. But for quite some time now I have had the problem in Retail WoW as well, that's what my request now refers to.

cheers
Aur0r4

**Comment by sylvanaar** [comment]
Do you have the disable flashing option on too.

The game itself has an option to disable tab flashing - is that on?

The chattabs module is pretty old - it may need an overhaul

**Comment by Aur0r4** [comment]
Umm... where can I find this option? Never noticed that and I can't find it anywhere.

**Comment by sylvanaar** [comment]
i don't know how it is set - but:

`/script CHAT_OPTIONS.HIDE_FRAME_ALERTS = true`

**Comment by sylvanaar** [comment]
Perhaps I will set that when you enable the disable flashing setting in Prat. Looks like it doesn't work for whispers - Nvm

**Comment by Aur0r4** [comment]
The "disable flashing" setting is already set in Prat, just checked that:
(Sorry its german client, so I can't provide you with english screenshots atm):

![image](https://user-images.githubusercontent.com/28149249/84654132-ef744980-af0e-11ea-8c48-7bbf06cf350b.png)

**Comment by Aur0r4** [comment]
I've found a way to reproduce this: 
1. hide chat-tabs
2. hide your interface
3. unhide your interface
4. chat tabs are not fading anymore until you mouse-over them

**Comment by Aur0r4** [comment]
Let me now if I can help somehow.
Would really like so see this fixed.

**Comment by Aur0r4** [comment]
I just wanted to say that the problem is fixed since 9.0. But in classic the problem still occurs.
