### ISSUE TITLE
Support custom filters for specific channels

### ISSUE THREAD

**Issue by chrishenzie** [sylvanaar/prat-3-0#101]
It would be nice to support custom filters for specific channels, not just all channels. For example, I would like to be able to block all messages containing "WTS|WTB" inside the "LookingForGroup" chat. Is this possible?

**Comment by sylvanaar** [comment]
You mind trying out the alpha?

https://www.wowace.com/projects/prat-3-0/files/2980673

**Comment by chrishenzie** [comment]
Just tried it out now, using my existing prat config.
- Extra Stuff -> CustomFilters -> Inbound -> Add Pattern named "Test"
- Provided "Search Pattern" and enabled "Block Message"
- Looking through "Search Channels", I don't see a way to specify which "Sub section" I want the filter to apply to for the input

Is the goal to provide a "Chatframe" and "Sub section" for the "Search Channels" section similar to what's in "Output"? Let me know if you need any other details.

**Comment by sylvanaar** [comment]
Had to revert for now - but the idea was that the channel names just appeared in the list of channels - like Party, Raid - etc. You can still refer back to the version I linked and we can work through the issues.

**Comment by sylvanaar** [comment]
> Is the goal to provide a "Chatframe" and "Sub section" for the "Search Channels" section similar to what's in "Output"? Let me know if you need any other details.

No - you create an output frame, and turn off all the chat channels on that frame - then we manually push messages there:

Example:

![](https://content.screencast.com/users/akhtar7512/folders/Snagit/media/c595c9a7-6ae5-4b29-8521-ae5463414595/06.21.2020-11.22.png)

**Comment by chrishenzie** [comment]
What I'm looking to do is filter out certain patterns from a specific chat channel. From my understanding it looks like if you select "Channel" in "Search Channels" it applies that filter to every channel you've `/join`ed.

Is there a way for me to say, "Block WTS / WTB from showing up in the LookingForGroup channel, but let it show up in Trade"? It seems like right now if I added this filter it would prevent this pattern from showing up in any channel.

**Comment by sylvanaar** [comment]
Yes I will have to add it as a feature and there are some complexities I have to deal with

**Comment by sylvanaar** [comment]
So, the UI for the options is kinda lousy, basically CHANNEL will still be available and will act as the defualt value for alll channels, however once you set a value for a particular channel, that channel will use its own option instead of the one for CHANNEL.

Please try the options out and see if you can make sense of them

**Comment by sylvanaar** [comment]
Please try the alpha and let me know if you see any issues
