### ISSUE TITLE
RegExp parsing in CustomFilters no longer works

### ISSUE THREAD

**Issue by speedwaystar** [sylvanaar/prat-3-0#102]
**Describe the bug**
RegExp in Extra Stuff->CustomFilters->Inbound no longer work

**To Reproduce**
Create an Inbound CustomFilter, for instance:

Filter Name: UBRS
Search Pattern: %f[%w][uU][bB][rR][sS]%f[%W]
Replacement Text: [Upper Blackrock Spire]

notice that after the last patch, when someone says UBRS in chat, it's no longer replaced with [Upper Blackrock Spire].

**Expected behavior**
in chat, UBRS should be replaced with [Upper Blackrock Spire]

*What happens now**
nothing

**Version Information (please complete the following information):**
Prat-3.0-3.8.22-1-g298db5f-classic
probably also in retail, although i haven't checked

**Comment by sylvanaar** [comment]
Was just an issue in a feature I was trying to add which meant you have to enable the channels you want individually. I am reverting that feature for now, but see #101

**Comment by speedwaystar** [comment]
I thought that might be the case when I noticed the other ticket re:
channels. Thanks.
