### ISSUE TITLE
TheLowDown scrolling down Combat log, no way to disable

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [sylvanaar/prat-3-0#103]
**Describe the bug**
TheLowDown is scrolling my combat log down to the bottom.  There is no option to turn it off for that frame.  I can't disable the Scroll module entirely because I want mouse wheel functionality.  Changing the delay for TheLowDown changes the amount of time before the combat log gets scrolled, so it's definitely TheLowDown doing it.  It definitely never did this in older versions of Prat, as I've accidentally had my combat log scrolled to the top for several raid bosses in a row.

**To Reproduce**
1. Set TheLowDown Delay to 1
2. Scroll combat log up any amount

**Expected behavior**
Have an option to disable TheLowDown for the combat log frame

**Version Information (please complete the following information):**
Prat-3.0-3.8.22
As an aside, /print (as recommended in this bug report) isn't a built-in WoW command.

**Comment by sylvanaar** [comment]
I have disabled it for the combat log for the time being
