### ISSUE TITLE
[Feature Request] Add an option to disable arrow key cycling in the History Module

### ISSUE THREAD

**Issue by Kolmarwow** [sylvanaar/prat-3-0#104]
Hi, first of all sorry if this is the wrong place to post this. I tried posting a Curseforge comment but it seems to be broken as it's giving me a "Parse Error" whenever i've tried posting a comment there for the past 1-2 days. 

With the History module enabled, you can open your chatbox and press the up/down arrow keys to cycle through old messages that you've sent in your current play session. I don't really want this enabled as it conflicts with another addon of mine, but I also don't want to disable the whole History module as I like the Scrollback feature. 

Would be neat to get an option to disable the arrow key cycling in the History module so that my problem is fixed. I'm playing on the Classic version of WoW if that helps.

**Comment by sylvanaar** [comment]
The option exists. Just switch back to the default ALT-Arrow keys in the Editbox module

![Option to disable](https://content.screencast.com/users/akhtar7512/folders/Snagit/media/2295c4f6-f4cf-4163-9ba5-fcd2236149a1/06.21.2020-09.59.png)

Let me know if this fixes your issue

**Comment by Kolmarwow** [comment]
Ah I didn't think to check the Editbox module, thank you. Unfortunately enabling the option doesn't seem to fix my problem but now this is more of an addon conflict issue than a feature request and I'd feel too demanding to ask you to fix that so feel free to close this issue if you wish. 

More information on the conflict if you decide you want to look at it: the addon is called [ItemAutocomplete](https://www.curseforge.com/wow/addons/itemautocomplete). What it does is it allows you to link items into chat more easily so that for example if I wanted to link Breastplate of Wrath I could begin typing into chat "[bre of wra" and then i can cycle through a list of items to add the item link into the editbox. 

The conflict comes when I use the arrow keys to cycle through the list, it starts cycling through my previous messages even with that setting enabled which is odd. This doesn't completely break the addon though as I can instead cycle through the list by pressing Tab or by using my mouse, so it's more of a minor inconvenience really.

**Comment by sylvanaar** [comment]
Try reloading your UI

**Comment by Kolmarwow** [comment]
Well now I feel stupid, that seems to have completely fixed this. Thanks for your patience & help!
