### ISSUE TITLE
[Classic]Report Player from chat context menu causes chatframe rollback

### ISSUE THREAD

**Issue by Road-block** [sylvanaar/prat-3-0#105]
**Describe the bug**
Doing a Report Player from the chat context menu (Yell in default chatframe in this instance)  
results in recent messages getting cleared so that chat appears to revert to an earlier time.  
Hard to say how many messages are removed from history (and the active chatframe) but the time gap was 43mins > 59mins (so all the messages in between those times are lost)  

When that happens the Copy Chat button also disappears (until /console reloadui)

No Lua errors present (I am running BugGrabber)

**To Reproduce**
1. Right-click report player from chat context menu.

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: 1.13.4 34835
 - Prat Version: Prat 3.0 (3.8.22-1-g298db5f)

**Addons you are running**
If possible list which addons you were using when the bug occurred.

**Comment by sylvanaar** [comment]
Need more details - and how does it differ from reporting without Prat?

**Comment by Road-block** [comment]
Hmm, I'll try to give more details.  

Assume your DEFAULT_CHAT_FRAME (General) has the social chats (guild/party/raid/whisper/say/yell/emotes). 

You chat in your party. Because it's party chat it's easy to monitor the flow of conversation and remember what's the last few things you said and got replies to.  
Now at some point you right-click report a player (for whatever reason, doesn't matter).  
Soon as the system message prints with "complaint registered" you see that the last several minutes of conversation are now missing from the chatframe.  
It's not a scrollup issue as scrolling to bottom does nothing (and besides that the system message with feedback about the report is visible/last message printed in the chatframe).    
But a bunch of recent party messages are now missing as if a partial :Clear() was performed on the chatframe.

Does that make sense about what the actual symptom is?  
I'll try to repro and clip it if not. (will be later / tomorrow perhaps though, raiding soon)

**Comment by sylvanaar** [comment]
I have heard people say that the default UI does this as well. It is done so they have some context This is my first guess - working as intended.

lets determine if this is Prat or the game - then we can discuss restoring those messages - Prat could keep a copy.

**Comment by Road-block** [comment]
That's quite possible, I didn't consider it might be happening without addons.

**Comment by Naxterra** [comment]
I see same issue on retail.

![image](https://user-images.githubusercontent.com/41871948/85469137-97dc7a80-b5ad-11ea-913a-e96e0d11f221.png)


![image](https://user-images.githubusercontent.com/41871948/85469156-9dd25b80-b5ad-11ea-916e-63b69ced828a.png)

Debug command had no result.

/pratdebugmsg
[23:58:36] empty result
[23:58:36] nil

**Comment by sylvanaar** [comment]
Yes but how about without Prat?

**Comment by Naxterra** [comment]
Without Prat it works normally.

Before reporting
![image](https://user-images.githubusercontent.com/41871948/85478184-0f190b00-b5bc-11ea-860b-e8005ca1a081.png)


After reporting
![image](https://user-images.githubusercontent.com/41871948/85478195-15a78280-b5bc-11ea-8dbc-6636254fe1cd.png)

**Comment by sylvanaar** [comment]
Here is the forum post I was thinking about:

https://eu.forums.blizzard.com/en/wow/t/reporting-a-player-deletes-your-chat-log/103076
