### ISSUE TITLE
[New Feature] AI based spam filtering

### ISSUE THREAD

**Issue by sylvanaar** [sylvanaar/prat-3-0#106]
New Feature - I have absorbed the addon SpamBayes in order to provide a basic spam filter to everyone.

 

The filter works via machine learning. You need to tell it what is spam and what isn't through the training interface.

 

To start open the filters module and enable the "AI Spam Filter", and the "AI Training"

![]![image](https://user-images.githubusercontent.com/114616/85496362-0232f200-b591-11ea-8450-78c2ce2d7d67.png)

You will see some new information on each chat line. There is a percentage score and links with + and -

 ![](https://content.screencast.com/users/sylvanaar/folders/Snagit/media/f69b3148-4ec9-4460-a482-643874b6d3c0/06.23.2020-17.12.jpg)

The score is how likely the AI thinks the chat line is spam. You can influence the AI by clicking the link -- (not spam) or ++ (spam)

 

Help the AI learn what is spam and what is not, and monitor its progress at learning. When you are happy that it is catching enough spam. Turn off training mode. Messages which had a RED percentage score will be filtered out.

 ![](https://content.screencast.com/users/sylvanaar/folders/Snagit/media/157f079a-ae20-493e-bccf-dc360fb64457/06.23.2020-19.59.jpg)

The best part is that you can train it to recognize spam if you want - or whatever else you would like. It does have limitations on what it can do - but for simple uses it should be OK

**Comment by sylvanaar** [comment]
Available in current release

**Comment by Revnn** [comment]
Hi, i would like to know what are the modules i need to leave enabled in order to use this feature.
I quite like the chat mod that elvui brings and im used to it, but i'd love to load prat with the minimum spec to use this feature.
Thanks in advance.

**Comment by sylvanaar** [comment]
> Hi, i would like to know what are the modules i need to leave enabled in order to use this feature.
> I quite like the chat mod that elvui brings and im used to it, but i'd love to load prat with the minimum spec to use this feature.
> Thanks in advance.

Hi. With ElvUI you must choose between Prat and ElvUI as your chat addon. You can see in my screenshot above I am running ElvUI myself. Unfortunately you can't run them both at the same time. That is just a limitation of both Prat and ElvUI.

**Comment by FilthySerf** [comment]
I have a question about this feature. I've noticed it working and properly increasing the percentage for chat messages that it believes are spam. Once it reaches 99% on people, will it eventually tip over to 100% and start filtering that spam from chat or do I have to manually increase it to 100%?

**Comment by sylvanaar** [comment]
> Once it reaches 99% on people, will it eventually tip over to 100% and start filtering that spam from chat or do I have to manually increase it to 100%?

I'm sorry if this part wasn't clear - those scores only appear during AI training mode - in that mode you see every message. When you turn training mode off - it filters all the messages with a score that was colored red.

**Comment by FilthySerf** [comment]
> > Once it reaches 99% on people, will it eventually tip over to 100% and start filtering that spam from chat or do I have to manually increase it to 100%?
> 
> I'm sorry if this part wasn't clear - those scores only appear during AI training mode - in that mode you see every message. When you turn training mode off - it filters all the messages with a score that was colored red.

Ah that makes more sense. Thank you

**Comment by Caedilla** [comment]
Does the AI filter work globally on all channels? I only notice the training options coming up on some channels (which includes system messages for some reason) 

Is there a way to select which channels the filtering is applied to afterwards? I only want to filter default public channels, not any sort of semi-private channel (group channels / guild, whispers)

**Comment by kalbert312** [comment]
Just wanted to chime in... thanks for this feature. Super nice.
