### ISSUE TITLE
Error When Logging in at Scrollback / OnModuleEnable

### ISSUE THREAD

**Issue by ap0yuv** [sylvanaar/prat-3-0#107]
**Describe the bug**
Since the latest Release i am getting an LUA Error when Logging in. I've tracked it down to an Issue with my Friends List
(See Swatter Trace below)

First Entry on my Friends List shows as "Unknown - Offline"

`/dump BNGetFriendInfo(1)` returns `nil`

Error is thrown due accessing null Index in `lookup` - Table

**Expected behavior**

Maybe checking for this corner case before adding to lookup

```
if battleTag ~= nil then
  lookup[battleTag] = accountInfo
end
```

**Swatter Trace**
```
Date: 2020-06-25 16:21:16
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\Scrollback.lua line 172:
   table index is nil
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:142
   (tail call): ?
   Prat-3.0\modules\Scrollback.lua:172: getBattlettagLookupTable()
   Prat-3.0\modules\Scrollback.lua:186:
      Prat-3.0\modules\Scrollback.lua:185
   [C]: gsub()
   Prat-3.0\modules\Scrollback.lua:225: RestoreLastSession()
   Prat-3.0\modules\Scrollback.lua:87: OnModuleEnable()
   Prat-3.0\addon\modules.lua:189:
      Prat-3.0\addon\modules.lua:178
   [C]: ?
   ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
```

**Addons you are running**
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BagBrother, v
  Bagnon, v8.3.5
  BagnonFacade, v8.3.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicLootAssistant, v
  Clique, vv1.0.3-classic
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  DejaClassicStats, v1304r002
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.10
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FishingBuddy, v0.7.3 Beta 5
  FiveSecondRule, v1.21
  GatherMate2, v1.45.5
  GBankClassic, v0.902
  Grid2, vr955
  Grid2LDB, vr955
  Grid2RaidDebuffs, vr955
  HealComm, v
  HealCommClassic, v
  HealOrganizer, vv2.5-alpha
  Immersion, v1.2.3
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LFGMatchMaker, v1.0.8
  LibClassicDurations, v1.59
  MapCoords, v0.33
  Masque, v8.2.8-Classic
  MasqueCaith, v8.2.6-Classic
  NovaWorldBuffs, v1.66
  OmniCC, v8.3.5
  outofrange, vv1.1
  Prat30, v3.8.25
  Prat30Libraries, v
  Questie, v5.10.3
  RCLootCouncilClassic, v0.10.1
  Scrap, v8.3.2
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpinxFocus, v1.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  VendorPrice, v1.3.5
  WeakAuras, v2.17.8
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>

**Comment by sylvanaar** [comment]
Thanks for the great bug report, and for following up!
