### ISSUE TITLE
MDT Link Parsing

### ISSUE THREAD

**Issue by Urzu77** [sylvanaar/prat-3-0#108]
Can't parse/import Method Dungeon Tool links again.  Unless this is some clever backlash against Method for the recent developments . . .

**Comment by sylvanaar** [comment]
No, there have just been a lot of changes recently.

#5 - Original issue

**Comment by sylvanaar** [comment]
Would you mind providing some information about what is broken with the links. What is the output you see?

Can you provide `/pratdebugmsg` that shows the link that is impacted.
