### ISSUE TITLE
Alias for inv whisper

### ISSUE THREAD

**Issue by Jinnai** [sylvanaar/prat-3-0#109]
I've set up an alias to whisper someone 'inv'. The person has setup autoinvite with 'inv' as the keyword. When I manually whisper the person it works fine but if I use the alias the autoinvite doesn't trigger.

**Comment by sylvanaar** [comment]
Please provide the definition of the alias you created.

How can I create the same one?

**Comment by Jinnai** [comment]
/l1 aliased to "/w allilayerone inv"
/l2 aliased to "/w allilayertwo inv"

created with

/alias l1 /w allilayerone inv
/alias l2 /w allilayertwo inv

**Comment by sylvanaar** [comment]
That's really unusual. I don't really have any way to set the test up like you would do it though.

I tried the commands, and they appear to be ok, they send the typical chat message with "inv" as the text.

If this is really the case there is something unusual going on.

You are able to see the message you send - it shows up in the chat

Turn your other addons off, and try again. Do you use WIM?

**Comment by Jinnai** [comment]
The messages show up in the chat. Nothing unusual. It just doesn't trigger the auto invite. I've tried it with no addons other than Prat and it is still the same issue. Not using WIM.

I have done some more testing and after enabling CopyChat I noticed that the aliased version adds a space at the end. This is why the autoinvite is not triggering. Please note that I did not add this space (accidently or otherwise) when I created the alias.
See:
https://i.imgur.com/ttuaTzX.png

**Comment by sylvanaar** [comment]
> I noticed that the aliased version adds a space at the end. This is why the autoinvite is not triggering.

Ok - I will take note - but space being added by the Blizzard UI code may just be something we have to live with.

You should ask the author of the auto-invite addon to trim extra spaces - that seems like the better option. I will look into it though.

**Comment by Jinnai** [comment]
Leatrix Plus had an update to trim extra spaces for the auto-invite feature. There are numerous other addons with such a feature though so if a fix from this side is possible that would be preferable.

**Comment by sylvanaar** [comment]
Please try the latest alpha version, and let me know if the issue is fixed.

**Comment by Jinnai** [comment]
Thank you, the latest version has fixed this issue.
