### ISSUE TITLE
Setting background opacity in Classic

### ISSUE THREAD

**Issue by reaktorblue** [sylvanaar/prat-3-0#11]
Is there a way to set the background opacity for all of the tabs in Prat? I'm currently doing this in the Blizzard UI and it's not user friendly at all.

- No indicator to see the specific opacity setting
- Unable to set all tabs uniformly, instead it's required to set each one manually
- Opacity settings don't seem to be persistent after logging off or disconnecting

I was hoping that this was something I could do within Prat but either it's not part of the functionality or I'm overlooking where these settings might be.

**Comment by sylvanaar** [comment]
Could be added to the Frames module - there is a related feature there that controls the opacity when you hover with your mouse. There could be a base opacity that sets all the chatframes to that.
