### ISSUE TITLE
Editbox settings broken

### ISSUE THREAD

**Issue by scarletwolf134** [sylvanaar/prat-3-0#110]
When trying to edit the edit box size nothing works and it just fucks up my edit box.
My normal vanilla edit box: 
![WoWScrnShot_062920_015342](https://user-images.githubusercontent.com/43823390/85978104-f2aa1380-b9ab-11ea-9845-858cebaa57e6.jpg)
Scuffed box that isn't getting any bigger except on the sides.(Yes I tried typing in to to see if it would drop down to become larger and nope it doesn't)
![WoWScrnShot_062920_015417](https://user-images.githubusercontent.com/43823390/85978177-2b49ed00-b9ac-11ea-9e02-20c138f2fb20.jpg)

(Please let me know if I'm doing anything wrong I couldn't find any videos explaining prats settings or how to use em, and or how to make this box big enough to hold more than one line of text. I'm pretty new to having any add-ons but the only chat add-ons I have are prat, emote splitter, and misspelled. But I also have narcissus and trp3 extended if that helps.)

**Comment by sylvanaar** [comment]
Prat doesn't have a multiline editbox feature - I have considered it - but it would cause trouble for users who don't understand how that would affect their editbox history and a few other things . So what you are trying to do isn't really supported. 

The settings do work - they just do something very different than what you were looking for mostly concerned with the style and appearance of the editbox they deal with the textures used on the border and inside the box (so you can change the look)
