### ISSUE TITLE
[Classic] Attempting to "Enter Battle" results in a error.

### ISSUE THREAD

**Issue by EyevouDeltree** [sylvanaar/prat-3-0#112]
When you queue for a battleground you are unable to click "Enter Battle" as an illegal operation appears saying:

"Prat-3.0 has been blocked from using an action only available to the Blizzard UI. You can disable this addon and reload the UI."

Clicking ignore and entering through the minimap icon does work, however.

**Comment by sylvanaar** [comment]
I basically rewrote Prat to try and fix that error. No luck.

**Comment by EyevouDeltree** [comment]
That's disheartening. :(

**Comment by sylvanaar** [comment]
I need a level 11 taint log to make any further progress on this issue.

Level 11 is only possible on the PTR

**Comment by EyevouDeltree** [comment]
It appears to be tainting with CURRENT_BATTLEFIELD_QUEUES (fairly obvious I guess) perhaps moving the the icon could be contributing to the issue?

**Comment by Martan404** [comment]
This is what BugGrabber tells me

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Prat-3.0-3.8.26-3-g1f17b47' tried to call the protected function 'AcceptBattlefieldPort()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `AcceptBattlefieldPort'
FrameXML\StaticPopup.lua:689: in function `OnAccept'
FrameXML\StaticPopup.lua:5002: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by Karakaz** [comment]
Would love to see this fixed :)
