### ISSUE TITLE
Feature idea: Chat history across characters

### ISSUE THREAD

**Issue by dieck** [sylvanaar/prat-3-0#113]
It would be great if chat history can be shared among characters.

If I log to an alt (with the same realm+faction), it would be nice to retain

- Trade Chat
- Looking for Group
- Guild Chat
- Whispers

in history so I can react to them / continue started conversations seamlessly.

Chat history is already stored, but on a per char basis.
So I see the last guild/trade/lfg chats from when the character was last logged in, but not the newest ones.

It seems History is stored in `Prat3CharDB.history`, with that being a `SavedVariablesPerCharacter`

`Prat.db` is already a AceDB-3.0 storage (from `SavedVariables` `Prat3DB` , so storing in e.g. `Prat.db.factionrealm.history` might be a good solution?

**Comment by sylvanaar** [comment]
Yes that would be the plan - use `factionrealm` to store the history.

Somewhere I had already started working on this.

**Comment by nickl1024** [comment]
Bump! Would really love to see this!
