### ISSUE TITLE
Memory Feature won't join Trade Channel after re-entering City

### ISSUE THREAD

**Issue by Breakerzeus** [sylvanaar/prat-3-0#114]
**Describe the bug**
There is an issue, that the Memory Feature tries to enter the Trade channel when you're outside of cities. It tries 3 times before giving up, resulting in chat massages:

> [13:23:30] <Titan> Registration process done. 29
> [13:23:33] [2]  Invalid channel name
> [13:23:38] [2]  Invalid channel name
> [13:23:45] [2]  Invalid channel name
> [13:23:52] Prat 3.0 (Memory) : Settings Loaded

After entering a city, the Trade channel is available again and should be joined automatically but isn't.
When disabling the Feature, the leaving and rejoining the Trade Channel is working fine.

**To Reproduce**
1. Go outside of a city
2. Reload UI or log out (log in after)
3. Wait for Setting to be loaded
4. See error messages in chat
5. go into the city again -> Trade channel won't be joined

**Expected behavior**
After leaving and re-entering a city, the trade channel should be joined automatically.

**Screenshots**
no need; messages above

**Version Information (please complete the following information):**
 - Wow Version: 8.3
 - Prat Version: 3.0-3.8.25

**Additional Information**
My suggestion with fixing this Issue is also maybe not trying to restart the whole "load settings thing" by leaving and rejoining the channels if one channel can't be joined. It's spamming the other users and seems weird. maybe just try to join the channel that has problems 3 times and then give up.

**Comment by sylvanaar** [comment]
I have put in a fix to the way channel restoration works that should eliminate most cases where this occurs, and improve the leave/join spam. Please try it out. You need to go to a city and restore your channels there first.

It might be useful to understand why it started the whole channel restore process. In case my change doesn't fix your particular case. The usual case is that as you logout - you leave some channels.

**Comment by Breakerzeus** [comment]
Yeah that solved the Issue. Thanks for that :)
Now no invalid channel message is popping up and when I'm outside of a city, the settings are loaded after 5s. Also when I look in the channel settings (Blizzard UI) I see that the trade channel is there but grey, means that it is not available. After I fly into a city, the trade channel can be accessed again. Good Job!
