### ISSUE TITLE
Option for chat tabs fading

### ISSUE THREAD

**Issue by reaktorblue** [sylvanaar/prat-3-0#13]
This may also be an option already within Prat and I may be overlooking where the setting is however, would it be possible to set the chat tab fading delay? Ideally, I'd like to set the tab fading delay to 0 so that all my chat tabs remain visible.

**Comment by sylvanaar** [comment]
You need to do it in the default UI for now.

**Comment by reaktorblue** [comment]
I haven't been able to locate an option for this with the default UI. Any idea where one might find that option?

**Comment by sylvanaar** [comment]
Go to the `ChatTabs` module and set both alpha sliders to 1. 

Seems like this is already implemented. Please reopen if it doesn't work
