### ISSUE TITLE
New Module Proposal: "Mentions"

### ISSUE THREAD

**Issue by sylvanaar** [sylvanaar/prat-3-0#14]
## The Prat @ mention.

Let's say a user wants to ping someone in the chat in the scope of say a GUILD message. There is no real way to do this with a single message - just hope they read or see it, or message them directly.

The @ mention will solve this through this basic functionality.

When a user is @ mentioned in a chat, a second <some kind of message> will be sent to that user notifying them of the @ mention - this should not be visible to users without an addon that supports it.

Perhaps in response to some of the complaints about spam - this needs to happen over the addon channel. or just local chat filtering, and end up in a **"Mentions tab"**

On the mentions tab, there should be "click-to-reply" links that will route messages back to the original channel or directly to the @ mentioner.

`Player1 mentioned you in <Channel>: "Message"`

### Enhancements to basic functionality

**Reply functionality** - replying to the mention notification routes the message to the Channel where the @mention was used.

**Clickable Mentions** - mentions should be turned into links, so they can be clicked - they should lead to whispering the person mentioned

**@ Mention Name Autocomplete**  would be nice if @ mentions autocompleted like most chat apps

**Notification Auto-Squelch** if the current frame that you are reading contains the message with the @ mention - the secondary whisper should probably be ignored

**Opt-In/Opt-Out** No need for this due to its opt-in nature (using the addon)

**Hash-tag support** Based on the updated proposal to have a "Mentions" tab, there could also be a tab for hashtag mentions - or the same tab.

### Consolidation

Prat has various modules that support the concept of highlight or mention alerting.

1) Popupmessage
2) Highlight
3) Custom Filters
4) Playernames (sort of)

While considering a new feature "@ mentions" I would like to consolidate a few modules into one.

**Comment by sylvanaar** [comment]
Nevcariel says:

> I would hate the concept of whispering someone, or being whispered for that matter, should just make a local module that reacts to @ strings instead of forcing it on people

> With such features have to also account for people on the receiving end, they have no button to easily opt out

**Comment by sylvanaar** [comment]
Foxlit says:

> If you have something on the receiving end listening for whispers, it might as well just flag the original mention to begin with.
18:01:37 (also, wouldn't the "hey I mentioned you!1!!" whisper die in scrollback just as easily as the original message if the recepient is not reading chat?)

**Comment by sylvanaar** [comment]
Gnarfoz says:

> doesn't prat already have a chat highlight module that does this

**Comment by Havenloft** [comment]
As someone who is horrible at reading chat I can say that I use the alert modules already and they seem to be more than enough for me.

**Comment by sylvanaar** [comment]
Znf

> Agree with nev, it would be annoying to be whispered out of the blue by someone @mentioning me, especially without giving consent first
19:14:14 Bundle it up in a library, for other people to implement it, if they want. Have it be opt-in. Use addon communication channel to check if X has opted in.
19:14:52 Maybe you want to enable it by default in prat, whatever. Just don't annoy people without the addon.

**Comment by mooreatv** [comment]
I think having a way to turn it off per source (user and/or channel) or globally is fine (that's how discord, github, etc... works for instance)

**Comment by mdridlon** [comment]
> As someone who is horrible at reading chat I can say that I use the alert modules already and they seem to be more than enough for me.

I use them as well but I would like to see something a little more robust and customizable.

**Comment by sylvanaar** [comment]
I would still like somehow to be able to include people without the addon in some way - but it would have to be an opt-in only type scenario, and limited to some kind of group relationship.

**Comment by ShaunDreclin** [comment]
Add an option to ignore loot messages

I hate getting pinged every time I roll on an item or when I loot an item containing one of my keywords in the name

[from #17]

**Comment by kevinhaas** [comment]
I was looking into how the casing is handled after running into the same issue as #15. After I noticed it didn't alert "PORTAL" when I added "portal" to the list, I looked at the code a bit and updated it to normalize casing on compare in `CheckText()`. It seems like this may have been played with at some point, as I see a few lines commented out related to this. It now works for my purpose, but I'd like to contribute as this new module gets fleshed out.

This is most likely what people experience when they report similar issues about a word not working. I saw quite a few reports on WowAce. I also noticed that "Portal" would work. Not sure if that's something to do with `Prat.GetNamePattern()`. I really didn't take a good look at that bit of code. I just threw in a quick fix for my use case.

I think normalizing the casing on compare is a good approach, as then users don't have to add the same string with different casing, which you can't even do at the moment. It seems like this may have been the intent from the beginning. The use case for matching on casing is pretty slim too. People will say portal/Portal/PORTAL as they please.

A simple note in the tooltip about how casing is handled and updating it to actually normalize would be great. 

Very neat code, btw.

**Comment by Under3D** [comment]
I've been using the popupmessages addon for monitoring chats for LFGs or items that I'm interested in. Prat's the only addon I've been able to find that can do this, even if it is borrowing functionality. Please consider adding keywords to monitor for.

**Comment by sylvanaar** [comment]
I have made the Mentions module to explore the concept of @messaging people from the message body.

So if I say in the channel "Prat"

"Hello @sylvanaar"

It will additionally send a whisper to sylvanaar with the message "Hello @sylvanaar"

It supports multiple @mentions in a single message

It supports tab complete in the editbox after you type @

Just a prototype

**Comment by sylvanaar** [comment]
I have gone ahead and made the mentions module available in the standard release. It is off by default, so you will need to enable it in the module control
