### ISSUE TITLE
9.0 pre-patch - attempt to call global 'GuildRoster' (a nil value)

### ISSUE THREAD

**Issue by zmoose** [sylvanaar/prat-3-0#140]
Seeing the following error with the 9.0 pre-patch

7x Prat-3.0-3.8.26\modules\PlayerNames.lua:1357: attempt to call global 'GuildRoster' (a nil value)
[string "@Prat-3.0-3.8.26\modules\PlayerNames.lua"]:1357: in function `?'
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@TomTom\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...aceTomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by domi1294** [comment]
I believe this is happening because at some point during BfA Blizzard moved many if not all of the guild functions to the `C_GuildInfo` namespace and now they deleted the deprecated functions that were still being used

**Comment by ghost** [comment]
Replacing the offending line with `C_GuildInfo.GuildRoster()` seems to suppress the error as a workaround. I assume this also preserves the functionality, but I didn't verify that.

**Comment by Vashidu** [comment]
#135 should fix some of the issues, seems others need to be updated still.

**Comment by voidzone** [comment]
Prat-3.0\modules\PlayerNames.lua

```
Line 1155:       GuildRoster()
Line 1323:     if IsInGuild() then GuildRoster() end
Line 1357:       GuildRoster()
```

**Comment by Krattan** [comment]
Classic is till using the old command so if you are going to fix it for both you need:
if Prat.IsClassic then
  GuildRoster()
else
  C_GuildInfo.GuildRoster()
end
