### ISSUE TITLE
Popup Message issue

### ISSUE THREAD

**Issue by Asaelem** [sylvanaar/prat-3-0#15]
The popup message nicknames seem to be case sensitive. I configured a nickname of "uld" and it pops up fine when it comes up in chat in lowercase. However, if someone types "ULD", it wont pop up. I then tried to add another nickname of "ULD" to account for this, but it doesnt differentiate between uppercase and lowercase in the nicknames list. Is there anyway to make it so no matter the upcase or lowcase letters, it will be recognized? 

 

Thank you!

**Comment by Asaelem** [comment]
it also seems to only be working in /1. I do not get notified for nicknames in /4 world chat

**Comment by sylvanaar** [comment]
This module is so old that it doesn't use the global pattern matching system. Therefore it should be rather easy to do a case-insensitive compare.

While I am at it - it should also detect "nicknames" as self-mentions, and not alert on them.

**Comment by sylvanaar** [comment]
All of this functionality is going to be merged into a new module called mentions

Please see #14
