### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Nimes2770** [sylvanaar/prat-3-0#150]
3x Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua:1323: attempt to call global 'GuildRoster' (a nil value)
[string "@Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua"]:1323: in function `fx'
[string "@Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua"]:1733: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Prat-3.0-3.8.26-3-g1f17b47\addon\addon.lua"]:673: in function <Prat-3.0\addon\addon.lua:613>
[string "=(tail call)"]: ?
[string "@FrameXML\ChatFrame.lua"]:3031: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

33x Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua:1357: attempt to call global 'GuildRoster' (a nil value)
[string "@Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua"]:1357: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Tovrin** [comment]
I'm getting the same

**Comment by seanhensley78** [comment]
BUG i am receiving-

Message: Interface\AddOns\Prat-3.0\modules\Editbox.lua:825: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 20:39:51 2020
Count: 1
Stack: Interface\AddOns\Prat-3.0\modules\Editbox.lua:825: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Prat-3.0\modules\Editbox.lua"]:825: in function `SetBackdrop'
[string "@Interface\AddOns\Prat-3.0\modules\Editbox.lua"]:753: in function `OnModuleEnable'
[string "@Interface\AddOns\Prat-3.0\addon\modules.lua"]:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
