### ISSUE TITLE
Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua:1357

### ISSUE THREAD

**Issue by Alandrias** [sylvanaar/prat-3-0#152]
25x Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua:1357: attempt to call global 'GuildRoster' (a nil value)
[string "@Prat-3.0-3.8.26-3-g1f17b47\modules\PlayerNames.lua"]:1357: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Nitrinax** [comment]
simple replace GuildRoster() with C_GuildInfo.GuildRoster() at line 1155, 1323, 1357 to fix this

**Comment by Stravides** [comment]
I see the simple fix and have applied it, but every time we get an update we have to keep doing this - any chance the update can have this in it.

**Comment by sylvanaar** [comment]
Please try with the version that just went out, let me know if you have any issues still

**Comment by knuspar** [comment]
Getting this with the newest release :-/

Message: Interface\AddOns\Prat-3.0\modules\PlayerNames.lua:1152: attempt to call field 'GuildRoster' (a nil value)
Time: Mon Oct 19 15:06:56 2020
Count: 1
Stack: Interface\AddOns\Prat-3.0\modules\PlayerNames.lua:1152: attempt to call field 'GuildRoster' (a nil value)
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
(tail call): ?
Interface\AddOns\Prat-3.0\modules\PlayerNames.lua:1152: in function `OnModuleEnable'
Interface\AddOns\Prat-3.0\addon\modules.lua:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
[C]: ?
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:630: in function <...Ons\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by Stravides** [comment]
Currently looking good for me.
TOC version 
## Version: 3.9.0

**Comment by KyrosKrane** [comment]
This is fixed in #167
