### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Melrina** [sylvanaar/prat-3-0#158]
I can't seem to load Prat via /prat. It isn't showing up on my Interface page. It's enabled and updated to latest version.

**Comment by MuTLY** [comment]
Make sure both folders (`Prat-3.0` and `Prat-3.0_Libraries`) are located inside the correct WoW version `Addons` folder, like so:

![image](https://user-images.githubusercontent.com/777006/98272711-260b3900-1f70-11eb-8913-fa31dc22ee99.png)
