### ISSUE TITLE
Playernames.lua 1320/1730 spam errors

### ISSUE THREAD

**Issue by bobbenx** [sylvanaar/prat-3-0#159]
getting spammed with this when i try to have class color in chat enabled. im using latest version.

3x Prat-3.0-3.9.0\modules\PlayerNames.lua:1320: attempt to call field 'GuildRoster' (a nil value)
Prat-3.0-3.9.0\modules\PlayerNames.lua:1320: in function `fx'
Prat-3.0-3.9.0\modules\PlayerNames.lua:1730: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Prat-3.0-3.9.0\addon\addon.lua:673: in function <Prat-3.0\addon\addon.lua:613>
(tail call): ?
FrameXML\ChatFrame.lua:2797: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by KyrosKrane** [comment]
This is fixed by #167
