### ISSUE TITLE
Highlight configuration?

### ISSUE THREAD

**Issue by sfjuocekr** [sylvanaar/prat-3-0#16]
There seems to be no way you can configure highlights?

For example my priests name is Kwakzalver, but everyone says "kwak".

I could use a CustomFilter to do this, but shouldn't there be a configuration side to highlights like the tooltip hints at?

![WoWScrnShot_091619_164135](https://user-images.githubusercontent.com/398018/64967510-efbcb700-d8a0-11e9-9332-7f58611e108a.jpg)

**Comment by sylvanaar** [comment]
Please see the new module proposal #14 and comment on it

btw Popupmessage allows nicknames

All of this type of functionality is going to be combined into one module
