### ISSUE TITLE
Guild chat bug since update

### ISSUE THREAD

**Issue by dmo90** [sylvanaar/prat-3-0#163]
Date: 2020-10-19 20:07:28
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\PlayerNames.lua line 1152:
   attempt to call field 'GuildRoster' (a nil value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   (tail call): ?
   Prat-3.0\modules\PlayerNames.lua:1152: OnModuleEnable()
   Prat-3.0\addon\modules.lua:189:
      Prat-3.0\addon\modules.lua:178
   [C]: ?

Seems to be working everywhere except for guild stuff.  When people chat in guild and when guildies come online the nameplates aren't showing

**Comment by bltpgermany** [comment]
Date: 2020-10-20 19:23:32
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\PlayerNames.lua line 1320:
   attempt to call field 'GuildRoster' (a nil value)
Debug:
   Prat-3.0\modules\PlayerNames.lua:1320: fx()
   Prat-3.0\modules\PlayerNames.lua:1730: ?()
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Prat-3.0\addon\addon.lua:673:
      Prat-3.0\addon\addon.lua:613
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2797: ChatFrame_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  ClassicLootAssistant, v
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10_deprecated
  CTBuffMod, v9.0.1.1
  CTCore, v9.0.1.1
  CTExpenseHistory, v8.3.7.1
  CTLibrary, v9.0.1.1
  CTMailMod, v9.0.1.1
  CTPartyBuffs, v9.0.1.1
  CTRaidAssist, v9.0.1.1
  CTTimer, v8.3.0.7
  CTUnitFrames, v8.3.7.1
  CTViewport, v8.3.7.1
  DBMCore, v1.13.61-16-gfeb2e20
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DruidBarClassic, v0.7.8
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.6.2
  FiveSecondRule, v1.23
  GatherMate2, v1.45.5
  GroupCalendar, v
  GuildRosterManager, v1.913
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  NovaWorldBuffs, v1.84
  OmniCC, v9.0.1
  Prat30, v3.9.0
  Prat30Libraries, v
  Questie, v6.1.0
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TargetHealth, v1.0.3
  ThreatClassic2, v2.24
  TidyPlatesThreatPlates, v10.0.1
  VendorPrice, v1.3.7
  WeakAuras, v3.0.4
  WeaponSwingTimer, v4.1.0
  WideQuestLog, v
  WrongCthunPlanner, v0.3.3
  BlizRuntimeLib_deDE v1.13.5.11305 <none>
  (ck=785)

**Comment by Hyphie24** [comment]
Replace 'GuildRoster' with **C_GuildInfo.GuildRoster** on lines 1152, 1320, & 1354

**Comment by KyrosKrane** [comment]
This is fixed by #167.

**Comment by Eurymachus** [comment]
When is the fix scheduled for release? <3

**Comment by Eurymachus** [comment]
I switched to alpha build and its fixed Ty <3
