### ISSUE TITLE
Bug with GuildRoster field since last update. I get this many times during a session. I am about to uninstall. That would be sad.

### ISSUE THREAD

**Issue by GoldenstarRemulos** [sylvanaar/prat-3-0#165]
Date: 2020-10-21 11:13:21
ID: 2
Error occured in: Global
Count: 2
Message: ..\AddOns\Prat-3.0\modules\PlayerNames.lua line 1320:
   attempt to call field 'GuildRoster' (a nil value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:146:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
   (tail call): ?
   Prat-3.0\modules\PlayerNames.lua:1320: fx()
   Prat-3.0\modules\PlayerNames.lua:1730: ?()
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Prat-3.0\addon\addon.lua:673:
      Prat-3.0\addon\addon.lua:613
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2797: ChatFrame_OnEvent()
   ...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:281:
      ...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:252
   ...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:311:
      ...s\WIM\Libs\LibChatHandler-1.0\LibChatHandler-1.0.lua:299
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AskMrRobotClassic, v2
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.3
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.5
  ConROC, v1.13.34
  DBMCore, v1.13.61-16-gfeb2e20
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7.1
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.55
  HealBot, v1.13.5.7
  HealBotData, v1.13.5.7
  HealBoten, v1.13.5.7
  HealBotExtraSkins, v1.13.5.7
  HealBotOptions, v1.13.5.7
  HealBotTips, v1.13.5.7
  honorspy, v1.7.7
  Informant, v8.2.6374 (SwimmingSeadragon)
  ISBoxer, v1.0
  ItemRack, v
  KKonferSK, v16
  NovaWorldBuffs, v1.84
  OmniBar, vv10.8
  OmniCC, v9.0.1
  PHGPCthunPlanner, v1.0
  Prat30, v3.9.0
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  QuartzProcs, v3.6
  Questie, v6.1.0
  RCLootCouncilClassic, v0.11.2
  ShadowedUnitFrames, vv4.2.3-Classic-3-g4aeee73
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.3.7
  WeakAuras, v3.0.4
  WIM, v3.8.15
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=68a)

**Comment by Hyphie24** [comment]
Replace 'GuildRoster' with **C_GuildInfo.GuildRoster** on lines 1152, 1320, & 1354 in PlayerNames.lua

**Comment by GoldenstarRemulos** [comment]
Had to do the opposite but it fixed itThanks-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 21/10/20, 11:24 am Hyphie24 <notifications@github.com> wrote:

   
  Replace 'GuildRoster' with C_GuildInfo.GuildRoster on lines 1152, 1320, & 1354 in PlayerNames.lua

**Comment by oathgg** [comment]
The reason why you have to change it to GuildRoster() instead of C_GuildInfo.GuildRoster() is because in WoW Classic (You're probably using that one) it's known as GuildRoster() instead of C_GuildInfo.GuildRoster().

https://wow.gamepedia.com/API_C_GuildInfo.GuildRoster

**Comment by Nomar111** [comment]
Thanks, that fixed it!
