### ISSUE TITLE
lua错误

### ISSUE THREAD

**Issue by nzcool** [sylvanaar/prat-3-0#166]
AddOns\Prat-3.0\modules\PlayerNames.lua:1152: attempt to call field 'GuildRoster' (a nil value)
Count: 1

Call Stack:
(tail call): ?
AddOns\Prat-3.0\modules\PlayerNames.lua:1152: in function `OnModuleEnable'
AddOns\Prat-3.0\addon\modules.lua:189: in function <AddOns\Prat-3.0\addon\modules.lua:178>
[C]: ?
...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:630: in function <...\AutoCombatLogger\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
AddOns\Prat-3.0\modules\PlayerNames.lua:1354: attempt to call field 'GuildRoster' (a nil value)
Count: 4

Call Stack:
(tail call): ?
AddOns\Prat-3.0\modules\PlayerNames.lua:1354: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by KyrosKrane** [comment]
Duplicate of #165 .
