### ISSUE TITLE
Private messages with "inv" in message are hidden from chat log

### ISSUE THREAD

**Issue by tgfish** [sylvanaar/prat-3-0#169]
**Describe the bug**
Every time I send a private message to someone that contains the text "inv" or "invite" the message is hidden from the chat log/chat box.

**To Reproduce**
1. Write a private message to someone that contains the text "inv" or "invite"
2. Notice the message doesn't show in the text box after sending

**Expected behavior**
If I message someone "hey send me an inv" then I will see that pink private message in my chat box/log

**Comment by hardasice** [comment]
I've noticed this isn't just for private messages. It doesn't show up in Officer chat. I've also had a friend whisper me with "inv" or "invite" in his message and it never showed on my chat log as well.

**Comment by Atomyslo1** [comment]
I have observed that turning off the hyperlink for the inv fixes the issue of hidden messages.

**Comment by poptix** [comment]
Date: 2020-10-23 23:08:54
ID: 1
Error occured in: Global
Count: 2
Message: ..\AddOns\Prat-3.0\modules\Invites.lua line 393:
   attempt to call field 'CanInvite' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [C]: CanInvite()
   Prat-3.0\modules\Invites.lua:393:
      Prat-3.0\modules\Invites.lua:386
   (tail call): ?
   (tail call): ?
   [C]: gsub()
   Prat-3.0\services\patterns.lua:197: MatchPatterns()
   Prat-3.0\addon\addon.lua:695:
      Prat-3.0\addon\addon.lua:613
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2797:
      ..\FrameXML\ChatFrame.lua:2790
   (tail call): ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
errMsg = "Interface\AddOns\Prat-3.0\modules\Invites.lua:393: attempt to call field 'CanInvite' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:597
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AutoLootPlus, v2.0.0-11302
  Bagnon, v8.3.5
  Bartender4, v4.9.0-16-g5a871a9
  buffOmat, v1.82
  CharacterStatsClassic, v3.6.5
  DBMCore, v1.13.61
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7.1
  Dejunk, v8.3.4
  Details, v
  DetailsTinyThreat, v
  EMAClassic, vv1.13.4-Release-v0.9(121029)
  ExRT, v4360
  GatherMate2, v1.45.5
  GDKPd, v
  GuildRosterManager, v1.913
  idTip, v8.2.1
  InFlight, v1.13.005
  InFlightLoad, v1.13.005
  ISBoxer, v1.0
  ItemAutocomplete, v1.0.6
  ItemRack, v
  LeatrixMaps, v1.13.82
  LeatrixPlus, v1.13.81
  LootReserve, v2020-10-03
  MikScrollingBattleText, v5.7.152
  MobKillCount, v7.1.0
  MoveAnything, v17.1.0
  NovaWorldBuffs, v1.84
  Prat30, v3.9.0
  Prat30Libraries, v
  Questie, v6.1.0
  ReStack, v0.1
  Restocker, v6.2
  RingMenu, v2.2.1
  SexyMap, vv5-classic
  Spy, v1.1.2
  statweightsclassic, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TradeLog, v
  TradeSkillMaster, vv4.10.13
  TradeSkillMasterAppHelper, vv4.0.9
  WeakAuras, v3.0.4
  WoWGatheringNodes, vWoWGatheringNodes_Classic_v1.0
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=4db)

**Comment by poptix** [comment]
C_PartyInfo.CanInvite doesn't seem to exist in Classic.

**Comment by tgfish** [comment]
Are those the hidden errors from a log? Not sure what to make of that.

**Comment by tgfish** [comment]
I should have mentioned I'm playing WoW Classic and have Pratt 1.13.2 installed.

**Comment by tgfish** [comment]
This issue seems to have resolved itself, can anyone else confirm the same?

**Comment by poptix** [comment]
Seems to have been a problem with the wrong version being posted on curseforge for classic.
