### ISSUE TITLE
I have always created a separate CHAT Tab for whispers but now even though I set it to do so won't show up... instead they now have all popup as individual chat whisper bubbles.  all of a sudden I have 8 tabs that I need to keep track of. Am I doing something wrong?

### ISSUE THREAD

**Issue by hamsouce** [sylvanaar/prat-3-0#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Information (please complete the following information):**
 - Wow Version: (current Retail or Classic) `/dump GetBuildInfo()`
 - Prat Version: You get this when you log in, or anytime `/dump Prat.Version`

**Addons you are running**
If possible list which addons you were using when the bug occurred.

**Comment by WanderingFox** [comment]
I had the same issue when 9.0 dropped. It doesn't appear to be prat that is doing this.

The WoW client itself reset everyone's "open whispers in a new window" option when the 9.0 pre-patch hit.

Check to see if Interface -> Social -> New Whispers is set to either "new window" or "both" and adjust as needed (inline would be the setting that only shows whispers as normal chat lines).

**Comment by hamsouce** [comment]
That worked like a charm.

Thank you! 

⁣Sent from Blue ​
