### ISSUE TITLE
Newcomer chat murloc icon missing

### ISSUE THREAD

**Issue by Isenblade** [sylvanaar/prat-3-0#171]
**Describe the bug**
The new murloc icon in the recently added newcomer chat is missing whenever I turn prat on

**To Reproduce**
1. Sign up to be a guide to get access to newcomer chat see the murloc icon on new players messages
2. Enable Prat and the icons vanish
3. Disable Prat and the icons come back

**Expected behavior**
I expect to be able to see the icons in the newcomer chat to identify new players and be able to answer their questions. Without getting confused with other experienced players also talking in the same channel. For images of what it should look like and how the system works [this wowhead guide](https://www.wowhead.com/news=318521/guide-mentor-system-help-new-players-starting-out-in-shadowlands) has some nice pictures.

**Version Information (please complete the following information):**
 - Wow Version: Retail 9.0.1.36322
 - Prat Version: 3.0-3.9.0

**Addons you are running**
These icons visibility consistently changes when I turn Prat on and off.

**Comment by WanderingFox** [comment]
Yeah it was reported a few days ago in #148 

I wrote a PR to fix it (#156) but it hasn't been accepted yet.

**Comment by Isenblade** [comment]
Ah ok cool I looked through the open bugs and somehow missed that one. Cheers for pointing it out.

**Comment by Isenblade** [comment]
Duplicate of #148
