### ISSUE TITLE
Prat-3.0_Libraries.toc - "## Interface:" should be 90001

### ISSUE THREAD

**Issue by PapaBearDoes** [sylvanaar/prat-3-0#177]
**Describe the bug**
It is currently set to
```
## Interface: 90000
```
This causes WoW to see the libraries as "Out of date" and therefore an error on load if "Load Out of Date Addons" is disabled.

![WoWScrnShot_102520_130619](https://user-images.githubusercontent.com/73200436/97116463-e36d7500-16c2-11eb-958e-a55594446823.jpg)

**Comment by PapaBearDoes** [comment]
Manually changing the TOC to read
```
## Interface: 90001
```
(after making sure the libraries are up-to-date) fixes the issue.

![WoWScrnShot_102520_130802](https://user-images.githubusercontent.com/73200436/97116512-419a5800-16c3-11eb-90f1-5825bf1c6534.jpg)

**Comment by takenek** [comment]
Thanks for report this :-) i just want to report this too :-) i need all the time Load out of date addons...

**Comment by MuTLY** [comment]
I guess the author kept it as "out of date" because not all libraries there are up to date? So this is actually **not** a bug.
