### ISSUE TITLE
..\AddOns\Prat-3.0\modules\PopupMessage.lua line 684:    attempt to call method 'SetBackdropBorderColor' (a nil value)

### ISSUE THREAD

**Issue by Dark-talon** [sylvanaar/prat-3-0#183]
Date: 2020-11-06 17:10:52
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\PopupMessage.lua line 684:
   attempt to call method 'SetBackdropBorderColor' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=(tail call)"]: ?
   [string "@Prat-3.0\modules\PopupMessage.lua"]:684: ?()
   [string "@Prat-3.0_Libraries\LibSink-2.0\LibSink-2.0.lua"]:801: func()
   [string "@Prat-3.0_Libraries\LibSink-2.0\LibSink-2.0.lua"]:519:
      ...ddOns\Prat-3.0_Libraries\LibSink-2.0\LibSink-2.0.lua:505
   [string "@Prat-3.0_Libraries\LibSink-2.0\LibSink-2.0.lua"]:525: Pour()
   [string "@Prat-3.0\modules\PopupMessage.lua"]:765: CheckText()
   [string "@Prat-3.0\modules\PopupMessage.lua"]:712: ?()
   [string "@AtlasLoot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@AtlasLoot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@AtlasLoot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@Prat-3.0\addon\addon.lua"]:723:
      Prat-3.0\addon\addon.lua:613
   [string "=(tail call)"]: ?
   [string "@..\FrameXML\ChatFrame.lua"]:3031:
      ..\FrameXML\ChatFrame.lua:3024
   [string "=(tail call)"]: ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v<%version%> (<%codename%>)
  AchievementsReminder, v
  AdvancedInterfaceOptions, v1.4.1
  AllPlayed, vv70100-1
  AngryKeystones, v
  AskMrRobot, v93
  AtlasLoot, vv8.13.00
  AtlasLootBattleforAzeroth, vv8.13.00
  AtlasLootBurningCrusade, vv8.13.00
  AtlasLootCataclysm, vv8.13.00
  AtlasLootClassic, vv8.13.00
  AtlasLootLegion, vv8.13.00
  AtlasLootMistsofPandaria, vv8.13.00
  AtlasLootWarlordsofDraenor, vv8.13.00
  AtlasLootWrathoftheLichKing, vv8.13.00
  Auctionator, v9.0.0.3
  Auctioneer, v8.3.BETA-4-1 (NzothsFolly)
  AuctioneerStatsOverTime, v8.3.BETA-4-1 (NzothsFolly)
  AuctioneerUtilDealFinder, v8.3.BETA-4-1 (NzothsFolly)
  AuctioneerUtilValuer, v8.3.BETA-4-1 (NzothsFolly)
  BadBoy, vv9.0.0
  BagBrother, v
  Bagnon, v9.0.4
  BagnonConfig, v
  Bartender4, v4.10.5
  BattlePetDailyTamer, v3.1.1
  BattlePetBinds, vr24
  BattlePetBreedID, vr211
  BlockChinese, vv1.9
  BrokerCurrency, v9.0.1.2
  CandyBuckets, v9.0.1.201029
  CanIMogIt, v9.0.1v1.28
  CompactRunes, v9.0.3
  CopyPasta2, v@project-version@
  CQuestCounter, v1.4
  CurrencySorter, v9.0.1.3
  DBMCore, v9.0.3
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v11.0.0
  Decursive, v2.7.7.1
  DejaCharacterStats, v900r1
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DialogKey, v1.8
  DynamicCam, v1.4.3
  EasyDeleteConfirm, v
  Enchantrix, v5.1.DEV.4632
  EnchantrixBarker, v8.3.BETA-4-1 (NzothsFolly)
  EpicMusicPlayer, vv7.2
  FishingBuddy, v1.11 Beta 1
  GarrisonMissionManager, vv59
  GatherMate2, v1.46.0
  Grail, v112
  GrailAchievements, v011
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GrailReputationsretail, v007
  GupPet, v8.0.3.01-g3
  HandyNotes, vv1.6.0
  HandyNotesAchievements, v0.5.0
  HandyNotesArgus, vv0.19
  HandyNotesAzerothsTopTunes, vv1.3.1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesLegionTreasures, v1
  HandyNotesTimelessIsleChests, v1.23
  HandyNotesVisionsOfNZoth, v41
  Informant, v1.13.6650 (SwimmingSeadragon)
  InstancePortals, v26
  KuiMedia, v
  KuiNameplates, v2.26.3e
  KuiNameplatesCore, v
  LargerMacroIconSelection, vv1.5.7
  LegionWardrobe, v33
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.152
  MinimalArchaeology, v9.0.3.3
  MogIt, v3.9.4
  MogItArtifact, v3.9.4
  MogItOneHanded, v3.9.4
  MogItOther, v3.9.4
  MogItPlate, v3.9.4
  MogItRanged, v3.9.4
  MogItTwoHanded, v3.9.4
  mOnArsWardrobeHelper, v1.20
  MountJournalEnhanced, v2.9.3
  MoveAnything, v18.0.3
  Oilvl, v9.0.1
  OmniCC, v9.0.2
  OPie, vXe 1a
  Outfitter, v6.0.0
  Overachiever, v1.1.1
  OverachieverCache, v1.1.1
  OverachieverTabs, v1.1.1
  OverachieverTrade, v1.1.1
  Pawn, v2.4.5
  PersonalLootHelper, v2.23
  PetJournalEnhanced, v2.9.30_90001_v2
  PetTracker, v9.0.1
  PetTrackerConfig, v
  PetTrackerJournal, v
  Postal, vv3.6.5
  Prat30, v3.9.1
  Prat30Libraries, v
  Quartz, v3.6.1
  RaidAchievement, v
  RaidAchievementOldModules, v
  RareScanner, v9.0.1.5
  Rarity, v1.0 (r700-release-2)
  RarityOptions, v
  Rematch, v4.11.6
  RSA, vr539-Release
  RSADeathKnight, v
  SavedInstances, v9.0.2
  Scrap, v9.0.1
  ScrapConfig, v
  SexyMap, vv9.0.8
  ShadowedUnitFrames, vv4.3.2
  Skada, v1.8.2
  SlideBar, v8.3.BETA-4-1 (NzothsFolly)
  Storyline, v3.2.1
  Stubby, v8.3.BETA-4-1 (NzothsFolly)
  TipTac, v20.11.04
  TipTacItemRef, v20.10.31
  Titan, v5.19.2.90001
  TitanBag, v5.19.2.90001
  TitanClock, v5.19.2.90001
  TitanGold, v5.19.2.90001
  TitanLocation, v5.19.2.90001
  TitanLootType, v5.19.2.90001
  TitanPerformance, v5.19.2.90001
  TitanRepair, v5.19.2.90001
  TitanVolume, v5.19.2.90001
  TitanXP, v5.19.2.90001
  TomTom, vv90001-1.1.5
  ToyBoxEnhanced, v2.5.2
  TradeSkillMaster, vv4.10.14
  TradeSkillMasterAppHelper, vv4.0.9
  TransmogTokens, v1.4.9
  WarPlan, v3.12a
  WeakAuras, v3.0.5
  Wholly, v080
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v9.0.1.90001 <none>
  (ck=f9b)

**Comment by clmcgrath** [comment]
getting a similar issue with chat bubbles calling the same function 
```
3132x Prat-3.0-3.9.1\modules\Bubbles.lua:479: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:479: in function `?'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:533: in function `IterateChatBubbles'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:437: in function `FormatBubbles'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:402: in function <Prat-3.0\modules\Bubbles.lua:398>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 update = <unnamed> {
 }
 EnableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 FormatCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:449
 defaultModuleLibraries = <table> {
 }
 IterateChatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:522
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 font = true
 name = "Prat_Bubbles"
 IsEnabled = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 FormatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:436
 OnModuleDisable = <function> defined @Prat-3.0\modules\Bubbles.lua:432
 APLyOptions = <function> defined @Prat-3.0\modules\Bubbles.lua:410
 throttle = 0.100000
 fontsize = 14
 IsModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 PL = <table> {
 }
 icons = true
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 format = true
 enabledState = true
 color = true
 shorten = false
 baseName = "Prat-3.0"
 OnModuleEnable = <function> defined @Prat-3.0\modules\Bubbles.lua:393
 RestoreDefaultsCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:516
 RestoreDefaults = <function> defined @Prat-3.0\modules\Bubbles.lua:440
 IterateModules = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 OnValueChanged = <function> defined @Prat-3.0\modules\Bubbles.lua:426
 transparent = false
 GetName = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Bubbles"
 defaultModuleState = true
 Disable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
frame = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 backdrop = <unnamed> {
 }
}
fontstring = <unnamed> {
 0 = <userdata>
 fontStyle = "NONE"
 font = "ElvUI\Media\Fonts\PTSansNarrow.ttf"
 fontSize = 11.900000
}
text = ""
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 backdrop = <unnamed> {
 }
}
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
MAX_CHATBUBBLE_WIDTH = 300
```

**Comment by ggeonu-abi** [comment]
310x Prat-3.0-3.9.1\modules\Bubbles.lua:479: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:479: in function `?'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:533: in function `IterateChatBubbles'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:437: in function `FormatBubbles'
[string "@Prat-3.0-3.9.1\modules\Bubbles.lua"]:402: in function <Prat-3.0\modules\Bubbles.lua:398>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 update = <unnamed> {
 }
 EnableModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 FormatCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:449
 defaultModuleLibraries = <table> {
 }
 IterateChatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:522
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 font = true
 name = "Prat_Bubbles"
 IsEnabled = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 FormatBubbles = <function> defined @Prat-3.0\modules\Bubbles.lua:436
 OnModuleDisable = <function> defined @Prat-3.0\modules\Bubbles.lua:432
 APLyOptions = <function> defined @Prat-3.0\modules\Bubbles.lua:410
 throttle = 0.100000
 fontsize = 14
 IsModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 PL = <table> {
 }
 icons = true
 SetEnabledState = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 format = true
 enabledState = true
 color = true
 shorten = false
 baseName = "Prat-3.0"
 OnModuleEnable = <function> defined @Prat-3.0\modules\Bubbles.lua:393
 RestoreDefaultsCallback = <function> defined @Prat-3.0\modules\Bubbles.lua:516
 RestoreDefaults = <function> defined @Prat-3.0\modules\Bubbles.lua:440
 IterateModules = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 OnValueChanged = <function> defined @Prat-3.0\modules\Bubbles.lua:426
 transparent = true
 GetName = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Bubbles"
 defaultModuleState = true
 Disable = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
frame = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 backdrop = <unnamed> {
 }
}
fontstring = <unnamed> {
 0 = <userdata>
 fontStyle = "NONE"
 font = "Fonts\2002.TTF"
 fontSize = 11.900000
}
text = ""
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 isSkinnedElvUI = true
 Name = <unnamed> {
 }
 backdrop = <unnamed> {
 }
}
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = 0.999998
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"
MAX_CHATBUBBLE_WIDTH = 300

**Comment by TheCheat54** [comment]
Would be nice to get a fix for this since the frame being created by the PopupMessage module is being derived and outside my ability to quickly fix on my own.
