### ISSUE TITLE
Feature Request: Fade slider for search and copy text icons

### ISSUE THREAD

**Issue by addonaddict** [sylvanaar/prat-3-0#190]
Hello,

Thanks for wonderful addon, using it for ages!
I have a minimalistic UI, my chat is 100% transparent when i am not using it, EXCEPT the 2 buttons that i just cannot fade out
I had to disable these options all together, but if u could incorporate an option to fade it out unless mousing over, that  would be wonderful as i do want to use it, but its ugly when there are buttons floating on your screen
![image](https://user-images.githubusercontent.com/73442541/103434167-74813080-4bcb-11eb-9cb5-ccacb5bdca7d.png)

Thank you and happy new years

**Comment by MrUzagi** [comment]
Yes, please. I second this.
