### ISSUE TITLE
only one character with issue

### ISSUE THREAD

**Issue by kaseyd24** [sylvanaar/prat-3-0#193]
Kind of a odd ball thing with one character..   Whispers keeping opening up a new chat box... all other toons, prat does not do that.. any way I can fix that?  the opening of whispers in a new window and me missing them in the main window is bothering me.m

**Comment by Lynxzes** [comment]
I have the same error as well with that NEW whisper window that keeps opening up

**Comment by kaseyd24** [comment]
anyone find a fix on this?
