### ISSUE TITLE
Hiding default UI timestamps without breaking Communities UI

### ISSUE THREAD

**Issue by Mitalie** [sylvanaar/prat-3-0#21]
I attempted to hide Blizzard's chat timestamps when using the Timestamps module in #3, but recently tried to use some Communities UI features and noticed they were broken by taint. I decided to take a step back and write down what exactly I wanted to fix and how it could be done without breaking other parts of the UI.

# Issue

For the purpose of timestamp handling, chat events can be grouped in three categories:
- Events that don't show default UI timestamp. Regardless of whether Prat processes them or passes them to default UI code, they receive their timestamps in Timestamps module's `AddMessage` hook.
- Events that do show default UI timestamp but are handled in Prat. Default UI tries to show the message with a timestamp, but Prat core's `AddMessage` hook prevents the output from reaching the chat frame and Prat can print its own version of the message, receiving a timestamp in Timestamps module's `AddMessage` hook.
- Events that do show default UI timestamp and are not handled in Prat. Default UI tries to show the message with a timestamp, Prat core's `AddMessage` hook lets it through, and Timestamps module's `AddMessage` hook adds a second timestamp. **These messages are displayed with two differently formatted timestamps, which I want to fix.**

# Communities UI

In the past, the trivial solution was to simply disable default UI timestamps whenever Prat's Timestamps module was being used. However, in patch 8.0 Blizzard added the Communities feature, with the UI using the same timestamp setting as chat. Because of this, forcibly disabling default UI timestamps is no longer something we want to do if a better solution can be devised.

# Failed solutions

- First solution, which I implemented in #3, was to only disable default UI timestamps when handling a chat event and restoring them afterwards. But it turns out that the Communities UI is not prepared to handle `CHAT_TIMESTAMP_FORMAT` variable being tainted. It creates the chat window with scrollback without any issues, as the chat window doesn't need to be secure, but then it proceeds to create buttons that need to be secure from the now tainted execution path. Tainted buttons cause features like editing community settings or player notes to fail. While Blizzard could fix this by wrapping the chat window creation in `securecall`, my understanding is that we shouldn't expect anything in a short time frame.
- The default UI timestamp format is persisted in the `showTimestamps` CVar, and those don't carry taint. Why can't we use that? The reason is obvious when reading default UI code, but I'm mentioning this idea for completeness. The CVar is not read directly where a timestamp is needed, but is cached in global lua variable `CHAT_TIMESTAMP_FORMAT` on `VARIABLES_LOADED` event and when changing the setting in the settings UI. We can't trigger either of those code paths securely, so the CVar is useless for rapidly toggling timestamps.

# Potential solutions

- Prat could process all the events that print a default UI timestamp, capturing the output and showing Prat's own version instead. The drawback is that it requires additional work to make sure these messages play nicely with all the other Prat modules and don't get mangled with unwanted formatting.
- The CVar accepts custom formats including color escape sequences, so we could store Prat's timestamp format in the CVar and have the default UI code use it directly. Prat would need to notice the events that don't print a default UI timestamp and add its own for those events only. Custom format works in the Communities UI too, which may be considered a feature. Drawbacks of using the CVar are that a UI reload is required after modification (or writing the global variable and tainting the Communities UI until next reload), and that the CVar persists outside of Prat and its Timestamps module being loaded, which may confuse users.
- Instead of *writing* the global `CHAT_TIMESTAMP_FORMAT` we can prevent the default UI chat code from *reading* it. By using `setfenv` on the original `ChatFrame_MessageEventHandler` we can redirect its global accesses to a separate table and set `CHAT_TIMESTAMP_FORMAT=false` (but not nil) while forwarding all other reads to the actual global environment using a metatable. The Communities UI continues to read the untainted actual global variable. For this method to work, we need a reference to the original function. This is only practical if we can do our `setfenv` before anyone else has hooked it.
- Instead of preventing default UI code from adding timestamps, we could just try to remove them afterwards with `string.gsub` or other string functions. For this to work reliably, we'd want to create our own instance of the timestamp using `BetterDate(CHAT_TIMESTAMP_FORMAT, time())`. This will work most of the time, but it's possible that the system time rolls to the next second between default UI's and our `time()` calls and we fail to match the default UI timestamp. The likelihood of this happening is very small, but it makes the solution feel dirty in my opinion.

I'm currently running the setfenv solution and it seems to work without issues, so I'm working on making a PR for it. I'm open for discussion on any other solutions too.

**Comment by sylvanaar** [comment]
Yes - the solution that has the most promise is using `TransformMessages` to add the timestamp after the message has been added to the chatframe
