### ISSUE TITLE
Error trying to right click name in chat and do a who lookup [Classic]

### ISSUE THREAD

**Issue by mascondante** [sylvanaar/prat-3-0#25]
Date: 2019-10-03 02:19:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\PlayerNames.lua line 876:
   attempt to call global 'SendWho' (a nil value)
Debug:
   [C]: SendWho()
   Prat-3.0\modules\PlayerNames.lua:876: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.2.2
  AtlasLootClassicDungeonsAndRaids, vv1.2.2
  AtlasLootClassicMaps, vv1.0.0
  ATTClassic, v0.1.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.15
  Bartender4, v4.8.8
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.09.01
  BrokerAFK, vr89
  BrokerEverything, v3.5.15-release
  BrokerRunSpeed, v1.0 (Classic)
  ChatLinkIcons, v2.0
  ClassicAuraDurations, v
  ClassicCastbars, vv1.0.9
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.10
  ClickLinks, v1.0.8
  Coordinates, v2.1.0
  DBMCore, v1.13.13b
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r026
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6454 (SwimmingSeadragon)
  ExpJunkieClassic, v1.0c
  EZJunk, v1.0.1
  GatherMate2, v1.45.5
  GTFO, v4.50.1
  Guidelime, v1.032
  GuidelimeBusteas160leveling, v1.7.0-Release
  GuidelimeSage, v1.0
  IAmAMerchant, v010000
  InFlightLoad, v1.13.003
  ItemTooltipProfessionIcons, v1.1.2
  LetMeCast, v1.3
  MaekorOverpowerAlert, v0.1
  Misspelled, v1.7.4
  OmniCC, v8.2.5
  Postal, vv3.6.0
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.2
  QuestFrameFixer, v1.1.1
  Questie, v4.1.1 BETA
  Recount, vv1.13.2d
  Scrap, v13.19
  ScrapSpotlight, v13.19
  SexyMap, vv3-classic
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Titan, v5.17.1.80100
  TitanBag, v5.17.1.80100
  TitanClock, v5.17.1.80100
  TitanGold, v5.17.1.80100
  TitanLocation, v5.17.1.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.1.80100
  TitanReloadUI, v1.0
  TitanRepair, v5.17.1.80100
  TitanShard, v4.3.1.30300
  TitanVolume, v5.17.1.80100
  TitanXP, v5.17.1.80100
  TomCats, v0.0.2
  TomTom, vv11302-1.0.7
  TownsfolkTracker, v1.0.6
  TrackResources, v0.5
  TradeSkillMaster, vv4.8.14
  TradeSkillMasterAppHelper, vv4.0.5
  WeakAuras, v2.15.2
  WIM, v3.8.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=9eb)

**Comment by Bratwurst99** [comment]
I get this error every single time I use the "Who Is?" option in the chats right click menu.

`Date:` 2019-10-30 09:49:42
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\PlayerNames.lua line 876:
   attempt to call global 'SendWho' (a nil value)
Debug:
   Prat-3.0\modules\PlayerNames.lua:876: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
dropdownFrame = FriendsDropDown {
 selectedLootMethod = "Loot: Group Loot"
 Right = FriendsDropDownRight {
 }
 Left = FriendsDropDownLeft {
 }
 lineID = "142"
 displayMode = "MENU"
 chatFrame = ChatFrame1 {
 }
 Button = FriendsDropDownButton {
 }
 Icon = FriendsDropDownIcon {
 }
 Text = FriendsDropDownText {
 }
 chatTarget = "Dirtfather"
 0 = <userdata>
 name = "Dirtfather"
 initialize = <function> defined @Interface\FrameXML\FriendsFrame.lua:244
 chatType = "CHANNEL"
 Middle = FriendsDropDownMiddle {
 }
 selectedLootThreshold = "Uncommon"
 which = "REPORT_PLAYER"
}
name = "Dirtfather"
(*temporary) = nil
(*temporary) = "Dirtfather"
(*temporary) = "attempt to call global 'SendWho' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CharacterNotes, v8.2.1
  ClassicAuraDurations, v
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Immersion, v1.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  ItemRackOptions, v
  LeatrixMaps, v1.13.36
  oGlow, v2.2.8
  OmniCC, v8.2.5
  Prat30, v3.7.36
  Prat30Libraries, v
  QuestGuru, v2.1.7
  Questie, v5.0.1 2 e2e80b7
  Scrap, v13.19
  ScrapMerchant, v13.19
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=59e)`
