### ISSUE TITLE
Incorrect Names in Chat History

### ISSUE THREAD

**Issue by reaktorblue** [sylvanaar/prat-3-0#31]
I'm noticing that when I log off of WoW Classic, when I log back in, the chat history has changed from people who have sent me a whisper who are on my account friends list. Character friends don't seem to be an issue but as an example, if before I logged off, I got a msg from "John Doe" when I log back in, the message would appear that it was "Jane Doe" instead.

Any idea what might be causing that?

**Comment by sylvanaar** [comment]
Right - this happens because blizzard hides the name from us.
