### ISSUE TITLE
 [Classic] target from context menu or chat

### ISSUE THREAD

**Issue by fgsfdss** [sylvanaar/prat-3-0#32]
Wrote this on Curseforge but not sure which one you actively use, so copied to here.

When attempting to target a player via right-clicking their name in the chat or sometimes by typing /target in the chat, the following popup appears and cancels the action:

![image](https://user-images.githubusercontent.com/5033279/67146321-36c80e80-f28a-11e9-8705-3da48a1273df.png)

**Comment by sylvanaar** [comment]
Fixed
