### ISSUE TITLE
[Feature Request] Disable certain player name highlighting

### ISSUE THREAD

**Issue by epon93** [sylvanaar/prat-3-0#33]
Forgive me if this already exists and I couldn't find it, but I'm looking for a way to disable highlights for certain names or certain name lengths (from the "Color Names Everywhere" feature under PlayerNames). I'm often seeing class color highlights for 2 and 3 letter character names that are common words/acronyms, like "at" or "dps" when they are obviously not being used in the context of referencing the character. So it would be nice to disable highlights for all 2 or 3 letter names, or to have a blacklist of names not to highlight.

**Comment by sylvanaar** [comment]
There is a slash command to blacklist certain names.

`/pratblacklist <name>`
