### ISSUE TITLE
Guild Controls [Classic]

### ISSUE THREAD

**Issue by RedDrumJay** [sylvanaar/prat-3-0#36]
I cannot change rank names or privileges when Prat is enabled. If I change the name of the rank, it changes  my rank (I'm the GM). If I switch to another rank and check a privilege, it changes my rank name, and doesn't change the privilege on the rank I was trying to change. It does not throw an error. It took trial and error to figure out which addon was causing the issue. From this error, it could be that it isn't playing nice with Zygor Guides:

Date: 2019-12-04 15:20:31
ID: -1
Error occured in: AddOn: ZygorGuidesViewerClassic
Count: 1
Message: Error: AddOn ZygorGuidesViewerClassic attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.
Debug:
   [C]: GuildControlSetRank()
   ..\FrameXML\FriendsFrame.lua:2514: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.1
  AtlasLootClassicData, vv1.4.1
  AtlasLootClassicDungeonsAndRaids, vv1.4.1
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BagnonConfig, v
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CensusPlusClassic, v1.13.2
  CharacterStatsClassic, v2.7
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.22
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.51
  GuildRosterManager, v1.831
  Informant, v8.2.6508 (SwimmingSeadragon)
  nUI, v1.13.2.31727.3
  PallyPower, vv1.1b-classic 
  Prat30, v3.7.41
  Prat30Libraries, v
  Questie, v5.2.3
  Recount, vv1.13.2f
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.16
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomTom, vv80205-1.0.8
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=55a)

**Comment by sylvanaar** [comment]
Duplicate cause #59
