### ISSUE TITLE
Highlight module uses wrong translations

### ISSUE THREAD

**Issue by Mitalie** [sylvanaar/prat-3-0#4]
Highlight module imports translations in the Achievements namespace. Because the subtable name doesn't match module name, `AddLocale` doesn't see any of the phrases. Later on, when hovering over the module in the settings UI, an error is thrown because `module_desc` phrase is missing.

The phrases and the namespace for Highlight module don't seem to exist in the localization system either. I'm not sure what would happen if I attempted to import a non-existing namespace, so no pull request.

**Comment by sylvanaar** [comment]
This module was released accidentally before it was completed. That is why it is like that. Shame on me

**Comment by sylvanaar** [comment]
I have addressed the issue here: b0dff013bc2713e2cdfda5ba4e4ec9eb22d219c4
