### ISSUE TITLE
More custom filters options

### ISSUE THREAD

**Issue by Klala** [sylvanaar/prat-3-0#44]
Can we get an option in custom filters to not include item links?
For example, I have "Lava" as a custom filter and all items that contain lava in them just get their link coloring really messed up.
Also, can we get the option to not have the custom filters case sensitive? I have to make a lot of filters just to filter the same words because of that.

**Comment by sylvanaar** [comment]
There is a thing called link protection that is supposed to prevent destroying item links - I will have to check if it is misconfigured.

For case insensitivity you do have the option of doing:

Match Cat cat CAT

`[Cc][Aa][Tt]`

**Comment by Klala** [comment]
![image](https://user-images.githubusercontent.com/1904932/72750229-efbd2280-3bc4-11ea-98e9-34d6eba70c44.png)
That is the thing I see with all checkboxes unchecked but the channel. I don't know how to make it ignore the links in the channels. I suspect it doesn't ignore links in other chat channels as well but I wouldn't know.

Also, could you explain where exactly I should put the matching characters? I didn't quite understand from what you said how or where I should put them.

**Comment by sylvanaar** [comment]
The link coloring is fixed - the pattern match priority was backwards for all these years!

**Comment by sylvanaar** [comment]
For example you have "North" as your search pattern.

You can put "[Nn][Oo][Rr][Tt][Hh]" and it will be case insensitive
