### ISSUE TITLE
ERROR WITH TODAY UPDATE 3.7.46 (2020-01-19)

### ISSUE THREAD

**Issue by emanueol** [sylvanaar/prat-3-0#45]
Date: 2020-01-20 18:42:31
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\addon\locales.lua line 70:
   Locale key .*[Tt]wink.*$ is not provided.
Debug:
   (tail call): ?
   [C]: error()
   Prat-3.0\addon\locales.lua:70:
      Prat-3.0\addon\locales.lua:69
   Prat-3.0\modules\AltNames.lua:2149: importGuildAlts()
   Prat-3.0\modules\AltNames.lua:1648:
      Prat-3.0\modules\AltNames.lua:1648
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  KalielsTracker, v0.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AskMrRobotClassic, v1
  Atlas, vv1.47.00.11303.00
  AtlasBattlegrounds, vv1.46.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasTransportation, vv1.46.03.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.61
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.1
  Bartender4, v4.8.9
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterNotes, v8.2.5
  CharacterStatsClassic, v3.1
  ClassicBlacklist, v1.1.5
  ClassicFriendBtn, v1
  ClassicThreatMeter, v1.10
  ClassTrainerPlus, v0.6-beta
  Clique, vv1.0.3-classic
  CoolLevelUp, v1.13.0.2
  DBMCore, v1.13.30
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  DejaClassicStats, v1303r001
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  FleecingTip, v113.1577(211219)
  GatherMate2, v1.45.5
  GatherMate2MapButton, v1.1
  GatherNotify, v1.6
  GatherTrackingReminder, v1.0
  GlobalIgnoreList, v1.13.3
  Grail, v106
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  Grid2, vr943
  Grid2LDB, vr943
  Grid2RaidDebuffs, vr943
  GuildRosterManager, v1.831
  GuildSearch, v8.2.1
  GuildTooltip, v2.13.11
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemAutocomplete, v1.0.6
  ItemRack, v
  ItemTooltipProfessionIcons, v1.1.5
  KiwiItemInfo, vv2.3.4
  LeatrixMaps, v1.13.44
  LibClassicDurations, v1.44
  MaxCam, vv2.4.2
  NugRunning, v1.13.34
  OmniCC, v8.3.1
  OPie, vAncient Walnut 6
  Pawn, v2.3.18
  Prat30, v3.7.46
  Prat30Libraries, v
  Puggle, v2.8
  PugLoot, vv1.1.1
  Quartz, v3.5-classic-5
  Questie, v5.5.1
  RCLootCouncilClassic, v0.6.0
  RealMobHealth, v2.18
  RecipeRadarClassic, v1.0.0.23
  RollTrackerClassic, v2.20
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic
  SimpleDing, vv1.1.1
  SimpleItemLevel, v1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18.2
  StatPriorityTracker, v0.0.3b
  Storyline, v1.13.2.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalentSequence, v2.0
  ThreatClassic2, v2.07
  TidyPlatesThreatPlates, v1.2.8
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicRestPlus, v1.0.0.1
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TitanProfession, vv1.2-classic
  TitanProfessionsMulti, v1.4
  TitanSkills, v1.7.0
  TitanSocial, v1.13.3
  TomTom, vv11303-1.0.9
  TownsfolkTracker, v1.0.7
  VendorPrice, v1.3.0
  WeakAuras, v2.16.1
  WhatsTraining, v1.8.7
  WhereToGatherClassic, v1.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=e0a)

**Comment by sylvanaar** [comment]
I have added some localization, and queued a new build - please confirm the fix
