### ISSUE TITLE
Method Dungeon Tools links not working

### ISSUE THREAD

**Issue by steel-raven** [sylvanaar/prat-3-0#5]
Since a couple of months the link support for Method Dungeon Tools is screwed with Prat. You can't click route links in chat.

Some amazing guy (unfortunately I don't know anymore if it was here in the comments or somewhere else) wrote a workaround for this.

 

The problem can be fixed via "patterns.lua" (line 147 to 171):

 

```
        debug("MatchPatterns -->", text, tokennum)
        -- Match and remove strings
    	if not text:match("|H.*|h") then
    		for _,v in ipairs(sortedRegistry) do
    		  if text and ptype == (v.type or "FRAME") then

    			if type(v.pattern) == "string" and (v.pattern):len() > 0 then
    			  debug("MatchPatterns :", v.pattern)

    			  if v.deformat then
    				text = v.matchfunc(text)
    			  else
    				if v.matchfunc ~= nil then
    				  text = text:gsub(v.pattern, v.matchfunc)
    				else
    				  debug("ERROR", v.pattern)
    				end
    			  end
    			end
    		  end
    		end
    	end
        wipe(sortedRegistry)

        debug("MatchPatterns <--", text, tokennum)
```

 

 

Please implement this finally, since I/we have to fix this manually every update.

 

Thanks.

**Comment by sylvanaar** [comment]
Does the problem go away if you turn either `on` or `off` the color names everywhere option in the `playernames` module?

This fix will break that part of that module - we need to find a better one.

I am more than happy to help, but I would like your support in seeing this through

Prat has some hidden features to help you help me.

If you can capture a debug dump of a message that isn't working - we can see what is actually happening.

If you issue the slash command `/pratdebugmsg` right after the message with the problem and post it here - we can take a look

**Comment by steel-raven** [comment]
Debugmsg right after someone send a route link to grop chat:


[18:27:30] [P] [120:Rekzar]: |HMethodDungeonTools-Rekzar+Kel'Thuzad[Freehold: Preset 5]
[18:27:37] CC="",
[18:27:37] CHANNEL="",
[18:27:37] PLAYER="|cff3ec5e9Rekzar|r",
[18:27:37] TYPEPOSTFIX=": ",
[18:27:37] Cc="",
[18:27:37] CHANNELNUM="",
[18:27:37] TYPEPREFIX="[P] ",
[18:27:37] Pp="|cffd8d8d8]|r",
[18:27:37] SERVER="",
[18:27:37] sS="",
[18:27:37] Ss="",
[18:27:37] PREPLAYERDELIM=":",
[18:27:37] pP="|cffd8d8d8[|r",
[18:27:37] cC="",
[18:27:37] PLAYERLEVEL="|cffd8bc3f120|r",
[18:27:37] MESSAGE="|HMethodDungeonTools-|cff3ec5e9Rekzar|r+Kel'Thuzad|h|cFFF49D38[|r|cFFF49D38Freehold: Preset 5]|h|r"
[18:27:37] GUID="Player-578-072586A7",
[18:27:37] LL="|h",
[18:27:37] pP="[",
[18:27:37] CHANLINK="channel:PARTY",
[18:27:37] TYPEPOSTFIX=": ",
[18:27:37] TYPEPREFIX="[Gruppe] ",
[18:27:37] Pp="]",
[18:27:37] PLAYERLINKDATA=":5:PARTY",
[18:27:37] TYPEID=4,
[18:27:37] PLAYERLINK="Rekzar-Kel'Thuzad",
[18:27:37] ORG=value,
[18:27:37] ACCESSID=3,
[18:27:37] Nn="|h",
[18:27:37] LANGUAGE_NOSHOW="",
[18:27:37] lL="|Hplayer:",
[18:27:37] CHATTYPE="PARTY",
[18:27:37] Ll="|h",
[18:27:37] PLAYER="Rekzar",
[18:27:37] NN="|h",
[18:27:37] MESSAGE="|HMethodDungeonTools-Rekzar+Kel'Thuzad|h|cFFF49D38[|r|cFFF49D38Freehold: Preset 5]|h|r",
[18:27:37] nN="|H",
[18:27:37] CHATGROUP="PARTY",
[18:27:37] EVENT="CHAT_MSG_PARTY"

**Comment by steel-raven** [comment]
![WoWScrnShot_083019_183154](https://user-images.githubusercontent.com/54681027/64036938-af490380-cb54-11e9-91ce-7a9ffa5947f4.jpg)

Surely has something to do with the coloring.

**Comment by sylvanaar** [comment]
Yeah ok I see what is happening - the link protection doesn't protect links without a color


EDIT: Oh no - I see - they put the color INSIDE the link - it is typically OUTSIDE the link do you see?

`|HMethodDungeonTools-Rekzar+Kel'Thuzad|h|cFFF49D38[|r|cFFF49D38Freehold: Preset 5]|h|r`

Would it be possible for them to create their link in the standard way?

`|cFFF49D38|HMethodDungeonTools-Rekzar+Kel'Thuzad|hFreehold: Preset 5]|h|r`

Prat has link protection for "standard" links. Is there a reason they can't match the standard link pattern (below)

This is the link protection code. Almost all links have a color - this is the first time I have run into one without one I guess.

```lua
	Prat.RegisterPattern({ pattern = "|c.-|H.-:.-|h.-|h|r",
			matchfunc=function(link) return Prat:RegisterMatch(link) end, 
			type = "FRAME", priority = 45 }, module.name)
```

And as I mentioned - you can turn off the Playernames options to "color names everywhere" and that should stop this from happening.

The other option might be that we add Prat link protection to their addon - so all prat users don't have to incur the processing costs of this additional link type.

**Comment by Nnoggie** [comment]
Got notified that a recent change has brought up issues with links again. I tried the suggestion of putting the color outside of the link but that did not seem to resolve the issue. Then i tried removing the color completely and the issue still persists. 
`newMsg = "|HMethodDungeonTools-"..characterName.."|h["..displayName.."]|h"`
https://i.imgur.com/HzOZ6Na.png
I was printing out the link below the message to show what the link is supposed to look like.
Could this perhaps stem from the fact that there is a character name embedded in the linkString?

**Comment by sylvanaar** [comment]
Hi according to the pattern the first part needs a colon

`|HMethodDungeonTools:CharName...`

Look at the pattern ` "|c.-|H.-:.-|h.-|h|r`

I don't want to be unreasonable - and I would like to support you in your efforts. **If you are dead set on your link format**, then I can help you add a "prat module" to your addon to install link protection for your users.

It's a pretty small thing - and I am more than willing to help out so long as I have your support

**Comment by sylvanaar** [comment]
So, the other authors convinced me that even though these links are in a "non-standard" format it is my job to support them. I do agree with them, so I have altered my link protection pattern to be less picky.

Let's hope this resolves your issue!

**Comment by steel-raven** [comment]
Thank you very much. 
And also thanks and cheers to Nnogga!
