### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by WetU** [sylvanaar/prat-3-0#5]
1x Prat-3.0-r1054      \addon\locales.lua:51: bad argument #1 to 'pairs' (table expected, got nil)
Prat-3.0-r1054      \addon\addon.lua:245: in function <Prat-3.0\addon\addon.lua:199>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

This error occured when login due to modules\Buttons.lua:203.

PL:AddLocale("koKR",  l)

Localization table is L (uppercase)

**Comment by sylvanaar** [comment]
Merged in Hg repository. Thank you!
