### ISSUE TITLE
prat-3.0 causing lag

### ISSUE THREAD

**Issue by zhuixinjian** [sylvanaar/prat-3-0#50]
when i got a lot of message, prat-3.0 causing lag.

**Comment by chernuw** [comment]
As example DBM messages on N'Zoth ¯\_(ツ)_/¯

**Comment by omggga** [comment]
Same with ZG bijou rolls. When someone recived item my fps drops up to zero lol...
When disabling Prat, everything is ok...

**Comment by sylvanaar** [comment]
Turn off the "Color Names Everywhere" option in Playernames. That is usually the issue.

If that is it - I am open to suggestions for how to auto-tune it. It is kind of a popular feature.

**Comment by sylvanaar** [comment]
I have stopped processing LOOT messages. This should fix the lag problem without the massive education issue about the setting.
