### ISSUE TITLE
[workaround] channelname fontsize in editbox

### ISSUE THREAD

**Issue by Aur0r4** [sylvanaar/prat-3-0#51]
Hi sylvanaar,

I've got this error in the versions after 3.7.43:
[https://abload.de/img/fontproblem9jkja.png](url)

The size of channelname and my text in the editbox is different and there is no way to change the channelname-size.

Any ideas?
Thanks a lot for your work! :)

Aur0r4 aka Yulu

**Comment by Aur0r4** [comment]
Hi!

This problem still exists. I have reset the configuration of Prat, but still it is not possible to have a uniform font size for the channel name and the input text in the chat editbox.

See the screenshot:
![fonzsize](https://user-images.githubusercontent.com/28149249/80801715-87abae80-8bad-11ea-84bf-b93211e90f15.PNG)

edit: It seems like, the channelname-size depends on the the settings made in the general font-size settings.

Another note:

I've tried so setup Prat from scratch with v3.7.43 but I was not able to let both, channelname and text to be the same size. When I use my old config, there is hat the correct size:

![chateditbox](https://user-images.githubusercontent.com/28149249/80806146-26d6a300-8bba-11ea-9f69-68ed952b9039.PNG)

**Comment by Aur0r4** [comment]
I have found a solution to my problem!
Thanks to your good documentation about changes to the AddOn I found out that this change here is for changing the "Header" font size:

https://github.com/sylvanaar/prat-3-0/commit/2c83ae94b5d844f73d5fb59d9058c3f4ee657d05

So I've removed line 269-272 from TellTarget.lua and the size is correct now.

```   
   -- set header's font
    local font, fontsize, style = ChatFrame1:GetFont()
    local header = _G[editBox:GetName().."Header"];
    header:SetFont( font, fontsize, style )
```
Maybe you can look into this.

**Comment by sylvanaar** [comment]
I see, your editbox fontsize is different than your chatframe. Looks like we need a better strategy here.

**Comment by sylvanaar** [comment]
Would you mind trying out this fix

```lua
`   -- set header's font 
    local header = _G[editBox:GetName().."Header"];
  
    local _, fontsize, _ = header:GetFont()
    local font, _, style = ChatFrame1:GetFont()
    
    header:SetFont( font, fontsize, style )
```

**Comment by Aur0r4** [comment]
This is working, thank you very much!

**Comment by sylvanaar** [comment]
Fixed in next release
