### ISSUE TITLE
prat block the report system

### ISSUE THREAD

**Issue by milotic** [sylvanaar/prat-3-0#52]
example a fake Gm whisper you, you right click report the player and this error pop up and report system is blocked, the only way to report a player is turning off prat

 

Date: 2020-03-01 01:01:10
ID: 16
Error occured in: AddOn: Prat-3.0
Count: 1
Message: Error: AddOn Prat-3.0 attempted to call a forbidden function (InitiateReportPlayer()) from a tainted execution path.
Debug:
[string "=[C]"]: InitiateReportPlayer()
[string "@..\FrameXML\HelpFrame.lua"]:341: HelpFrame_ShowReportCheatingDialog()
[string "@..\FrameXML\UnitPopup.lua"]:1796: func()
[string "@..\FrameXML\UIDropDownMenu.lua"]:889: UIDropDownMenuButton_OnClick()
[string "*:OnClick"]:1:
[string "*:OnClick"]:1
Locals:
None

**Comment by wiesshund** [comment]
Same kind of issue happens trying to accept a battleground
and also when trying to add notes to guild members

**Comment by orionshock** [comment]
This is probably not a Prat issue. When any Addon touches the "UIDropDownMenu" system, it introduces Taint and the first addon to load the ace framework often get's blamed.

**Comment by wiesshund** [comment]
wiped all addons and wtf folder
reinstalled prat
still does this.

Not sure what else to try?

**Comment by orionshock** [comment]
the AltNames, Copy Chat, PlayerNames modules all touch the "UIDropDownMenu" system as well as the unitpopupmenus.lua file.

This is more of a blizzard fkup than anything. However as prat does interact with the UIDropDownMenu system, the author needs to recode it to use one of the alternative libraries or pull those features altogether.

**Comment by sylvanaar** [comment]
Sorry I am so slow to fix this. I have tried to eradicate all references to UIDropdown and UnitPopup. I had done it before but I think I was not thorough enough last time
