### ISSUE TITLE
Parts of words are class-colored when preceded with non-English characters

### ISSUE THREAD

**Issue by happyzebra** [sylvanaar/prat-3-0#53]
Prat colors part of strings that includes player names if non-English characters are right before it, such as öåä etc. When those characters are after the player string it works fine. Best described with a screenshot:

![image](https://user-images.githubusercontent.com/39415468/76576532-a0a7b580-64c2-11ea-86ce-c7889e17bc4e.png)

This is on classic and latest version of the addon (always been like this on classic).
I haven't tested on retail.

**Comment by sylvanaar** [comment]
This is related to an imperfect match of UTF8 characters.

`MULTIBYTE_FIRST_CHAR = "^([\192-\255]?%a?[\128-\191]*)"`

**Comment by sylvanaar** [comment]
```
[22:04:18] Prat 3.0 (DEBUG): >> print(tostring(Prat.GetNamePattern("bad")))
[22:04:18] Prat 3.0 (DEBUG): "%f[%a\192-\255][Bb]ad%f[^%a\128-\191]"
```

That matches in `öbad ` (`"\195\182bad"`) but not `abad`

I see why, \182 is considered a non-match, so when it sees the b following it, it starts matching on the transition.

A fix is to include all > 128

` "%f[%a\128-\255][Bb]ad%f[^%a\128-\191]"`

Will need extensive testing

**Comment by sylvanaar** [comment]
Resolved
