### ISSUE TITLE
[WOW Classic] Displaying Alt Names in Chat does not work

### ISSUE THREAD

**Issue by Runkel79** [sylvanaar/prat-3-0#54]
The AltNames Module imports Alt names correctly and displays Alt Names in Tooltips but not in Chat where it would be important.
I tried deactivating all other Addons but got the same result, installing "LibAlts" didn't help either (was worth a try). :)

The Module causes no LUA errors so theres no Error report i can post, it just doesn't work.

I'm playing on the German WOW Classic Client if that's of any significance.

Thanks for your attention. :)

**Comment by l8nite** [comment]
Yea, I also have seen this. Sometimes the alt name shows up properly, and then other times it does not.
