### ISSUE TITLE
Rerout Output

### ISSUE THREAD

**Issue by dennyh** [sylvanaar/prat-3-0#57]
Rerouting output from a custom filter to anything other than a popupwindow does not work.

I would like to be able to filter out some messages and put them in a channel of my choosing.

**Comment by sylvanaar** [comment]
There are limitations placed by Blizzard as follows.

> SendChatMessage automation disabled in public/private chat channels
> 
> It’s ALSO disabled from SAY/YELL out in world.
> 
> It’s permitted in raid/party/guild chat, and SAY/YELL within instances.

I corrected a couple bugs if you want to try with these restrictions

**Comment by sylvanaar** [comment]
This is fixed within the limitations defined by Blizzard. Closing
