### ISSUE TITLE
No way to set font size for new whisper windows.

### ISSUE THREAD

**Issue by l8nite** [sylvanaar/prat-3-0#60]
I have this setting in my Interface options:

![image](https://user-images.githubusercontent.com/1711530/81121485-b6928f00-8ee3-11ea-9605-d9be87b82792.png)

I'd like to apply a default font style / size to the new whisper window:

![image](https://user-images.githubusercontent.com/1711530/81121585-ec377800-8ee3-11ea-8b46-ed86ed1b3e8c.png)

**Comment by sylvanaar** [comment]
Hmm, works ok here. I wonder what the difference is in your game

**Comment by sylvanaar** [comment]
Most likely the issue the OP was having has been fixed in the recent batch of fixes
