### ISSUE TITLE
Arrow Up adds extra spacing

### ISSUE THREAD

**Issue by JonasWG** [sylvanaar/prat-3-0#61]
If you attempt to resend a message bu using Arrow Up key combination an extra space is added to the message. This is especially annoying if you are using for example WeakAurass command "/wa" in the chat as the new output will be " /wa", and if you repeat this message "  /wa" etc..

**Comment by sylvanaar** [comment]
This doesn't happen when I do it. I can resend the /wa command. Perhaps another addon is doing it?

What version of the game?

**Comment by sylvanaar** [comment]
I found a solution. Looks like sometimes the chatType is nil
