### ISSUE TITLE
Create A UI for the Search Feature

### ISSUE THREAD

**Issue by sylvanaar** [sylvanaar/prat-3-0#63]
In order to surface the search functionality, placing a search bar on the chatframe would be useful.

The search feature would have 2 modes:

1. "search in the chat" where it would scroll through the chat highlighting matches, 
2. 'list all matches" where it would just output the list of matching lines somewhere

Could also have the feature of case-insensitive matching - or allowing patterns

**Comment by sylvanaar** [comment]
![image](https://user-images.githubusercontent.com/114616/82750077-a7746380-9d62-11ea-9fb7-02f63712596d.png)

Here's the prototype. I will make it available shortly.

**Comment by sylvanaar** [comment]
Available to try in 3.7.76

**Comment by sylvanaar** [comment]
First feedback is as expected. The ability to move the search box

**Comment by Regikid** [comment]
Is there a way to turn the search function off? or move it?

**Comment by sylvanaar** [comment]
> Is there a way to turn the search function off? or move it?

@Regikid There sure is. Go to "Module Control" and disable the Search module.

If you were to move it - where would you move it. I am trying to find a place for it that the majority of people could live with. Then I will make it movable

**Comment by KyrosKrane** [comment]
Perhaps make it an icon like the CopyChat function? If you click the icon, the actual search box opens. That way, it's less invasive and confusing if you just happen to mouse over that spot. I'd say make it positionable like the copy icon as well.

**Comment by sylvanaar** [comment]
@KyrosKrane ok  - I will try keeping the search box our of the way until it gains focus by being clicked.

**Comment by sylvanaar** [comment]
I think I am going to call it good in its current implementation.
