### ISSUE TITLE
Whispers don't show up in the addon after 3.7.72

### ISSUE THREAD

**Issue by Mukus91** [sylvanaar/prat-3-0#64]
Disabling the addon fixes it, but while the addon is enabled whispers don't show up in the chat at all, not sent or recieved ones. I tried clearing saved variables without luck and reinstalling the addon entirely doesn't fix it either. 

Sorry for not posting on Curseforge but the site sucks and throws errors when I submit comments.

**Comment by hansendevdk** [comment]
It seems like the sendchat api could be the issue.

**Comment by hansendevdk** [comment]
/say works, /yell works, and all the other channels. It's only whispers that are gone.

**Comment by Rinkor14** [comment]
I'm actually having the issue of none of the chats showing up.

**Comment by Krayde** [comment]
I can't see the chat, and i mean nothing! No /s, no /2, no /g, literally nothing! Only time i can see the chat is when i disable the addon completely, and that makes the game unplayable seeing i play the AH.
Is there a fix to this or do we need to wait for a new version?

I've tried downloading previous versions but it doesn't work.
I'm playing on **CLASSIC**  and here is the error:

Date: 2020-05-20 13:24:25
ID: -12
Error occured in: Global
Count: ∞
Message: ..\AddOns\Prat-3.0\services\chatsections.lua line 609:
attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Debug:
[C]: ReplaceIconAndGroupExpressions()
Prat-3.0\services\chatsections.lua:609: SplitChatMessage()
Prat-3.0\addon\addon.lua:591:
Prat-3.0\addon\addon.lua:566
(tail call): ?
..\FrameXML\ChatFrame.lua:2792:
..\FrameXML\ChatFrame.lua:2785
(tail call): ?
[string "*:OnEvent"]:1:
[string "*:OnEvent"]:1
Locals:

AddOns:
Swatter, v8.2.6511 (SwimmingSeadragon)
AdvancedInterfaceOptions, v1.3.4
Altoholic, vClassic v1.13.4-014
AntiDaze, v7
Atlas, vv1.47.00.11303.00
AtlasBattlegrounds, vv1.46.00.11303.00
AtlasClassicWoW, vv1.47.00.11303.00
AtlasDungeonLocs, vv1.47.00.11303.00
AtlasTransportation, vv1.46.03.11303.00
AtlasLootClassic, vv1.5.1
AtlasLootClassicData, vv1.5.1
AtlasLootClassicDungeonsAndRaids, vv1.5.1
AtlasLootClassicMaps, vv1.0.0
AucAdvanced, v8.2.6471 (SwimmingSeadragon)
AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
AucStatSimple, v8.2.6501 (SwimmingSeadragon)
AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
BagBrother, v
Bagnon, v8.3.5
BeanCounter, v8.2.6505 (SwimmingSeadragon)
BetterVendorPrice, vv1.13.04
CharacterTooltip, v1.0.4
ClassicAuraDurations, v1.13.56
ClassicCastbars, vv1.3.6
ClassicCastbarsOptions, v
DataStore, vv1.13.013
DataStoreAuctions, vv1.13-013
DataStoreCharacters, vv1.13-013
DataStoreContainers, vv1.13-013
DataStoreCrafts, vv1.13-013
DataStoreInventory, vv1.13-013
DataStoreMails, vv1.13-013
DataStoreQuests, vv1.13-013
DataStoreReputations, vv1.13-013
DBMCore, v1.13.45-20-g91bab6d
DBMDefaultSkin, v
DBMStatusBarTimers, v
Details, v
DetailsStreamer, v
DetailsTinyThreat, v
Dominos, v8.3.9
DominosCast, v
DominosProgress, v
DominosRoll, v
DRList10, vv1.1.2
Enchantrix, v8.2.6506 (SwimmingSeadragon)
EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
ExtendedCharacterStats, v2.2.1
FishingBuddy, v0.7.3 Beta 5
FleecingTip, v113.1672(060320)
Flexi, vFlexi 1.4e
GatherMate2, v1.45.5
idTip, v8.2.1
Informant, v8.2.6508 (SwimmingSeadragon)
ItemRack, v
KuiMedia, v
KuiNameplates, v
KuiNameplatesCore, v
LeatrixMaps, v1.13.64
LeatrixPlus, v1.13.64
LibStub, v
Mapster, v1.8.5
MobInfo2, v8.3.0 Classic
NovaWorldBuffs, v1.57
OmniCC, v8.3.5
Pawn, v2.3.26
Peggle, v2.2.8
Prat30, v3.7.72
Prat30Libraries, v
PreyStation, v
Questie, v5.10.3
RecipeRadarClassic, v1.0.0.23
Scrap, v8.3.2
SlideBar, v8.2.6509 (SwimmingSeadragon)
Spy, v1.0.27
Stubby, v8.2.6510 (SwimmingSeadragon)
TFTB, v1.10
TomTom, vv11304-1.1.2
TrackSales, v0.1.5
TradeSkillMaster, vv4.9.35
TradeSkillMasterAppHelper, vv4.0.8
tullaRange, v8.3.2
WeakAuras, v2.17.5
WeaponSwingTimer, v4.1.0
BlizRuntimeLib_enUS v1.13.4.11304 <none>
(ck=a00)

**Comment by Krayde** [comment]
Chat is completely broken, nothing can be seen. No whispers, not say, yell, trade, LFG - literally nothing! 
Only time i can see the chat is when disabling the addon entirely, which is a big no go (chat unplayable without the addon, especially when you play the AH :)).

I'm playing on **CLASSIC** and here is the swatter error i receive:

Date: 2020-05-20 14:23:04
ID: 2
Error occured in: Global
Count: ∞
Message: ..\AddOns\Prat-3.0\services\chatsections.lua line 609:
   attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Debug:
   [C]: ReplaceIconAndGroupExpressions()
   Prat-3.0\services\chatsections.lua:609: SplitChatMessage()
   Prat-3.0\addon\addon.lua:591:
      Prat-3.0\addon\addon.lua:566
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2792:
      ..\FrameXML\ChatFrame.lua:2785
   (tail call): ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

**Comment by Krayde** [comment]
Fix: Go into the addon in Twitch client, click Versions, download version 3.7.71-classic - DONE!
#thankmelater

**Comment by hansendevdk** [comment]
> 
> 
> Fix: Go into the addon in Twitch client, click Versions, download version 3.7.71-classic - DONE!
> #thankmelater

Can I thank you now? I didn't even realize twitch had that functionality.

**Comment by sylvanaar** [comment]
New build pushed - Sorry!

**Comment by Krayde** [comment]
> 
> 
> > Fix: Go into the addon in Twitch client, click Versions, download version 3.7.71-classic - DONE!
> > #thankmelater
> 
> Can I thank you now? I didn't even realize twitch had that functionality.

Yes you can!
