### ISSUE TITLE
[Classic] gbaa2804 alpha - ReplaceIconAndGroupExpressions error

### ISSUE THREAD

**Issue by Road-block** [sylvanaar/prat-3-0#65]
```
151x Prat-3.0-3.7.72-3-gbaa2804\services\chatsections.lua:609: attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Prat-3.0-3.7.72-3-gbaa2804\services\chatsections.lua:609: in function 'SplitChatMessage'
Prat-3.0-3.7.72-3-gbaa2804\addon\addon.lua:591: in function <Prat-3.0\addon\addon.lua:566>
(tail call): ?
FrameXML\ChatFrame.lua:2792: in function 'ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
```

**Comment by Road-block** [comment]
It appears that to have it work on both clients a short-circuit like this is necessary.
```lua
local ReplaceIconAndGroupExpressions = _G.C_ChatInfo.ReplaceIconAndGroupExpressions or _G.ChatFrame_ReplaceIconAndGroupExpressions
```

Or a game version conditional check.

**Comment by Road-block** [comment]
Just a note that #68 , #67 and #66 are duplicates of this.
**Edit:** #64 as well though it didn't have the error on the ticket so that's my excuse 😛

**Comment by Road-block** [comment]
So the way to fix this for people that do not want to downgrade is go to this [services/chatsections.lua#L19](https://github.com/sylvanaar/prat-3-0/blob/baa280464ebab87a17feb00f88484716696278db/services/chatsections.lua#L19) and add
```lua
local ReplaceIconAndGroupExpressions = _G.C_ChatInfo.ReplaceIconAndGroupExpressions or _G.ChatFrame_ReplaceIconAndGroupExpressions
```
Then go to [services/chatsections.lua#L609](https://github.com/sylvanaar/prat-3-0/blob/baa280464ebab87a17feb00f88484716696278db/services/chatsections.lua#L609) and make that line look like this
```lua
s.MESSAGE = ReplaceIconAndGroupExpressions(s.MESSAGE, arg17, not _G.ChatFrame_CanChatGroupPerformExpressionExpansion(chatGroup))
```

Save the file and reload the game.

**Comment by sylvanaar** [comment]
New build pushed - sorry about that
