### ISSUE TITLE
[Classic] Game freezes after last update

### ISSUE THREAD

**Issue by trincamckee** [sylvanaar/prat-3-0#66]
Updated Prat this morning to 37723 from 3768 or 9 (not sure), and the game became unplayable, the image would freeze every couple of seconds.

 

Found out it was Prat after disabling and enabling addons, reverted back to 3769 and all is well.

**Comment by Reydas** [comment]
The addon has worked fine to this day. At lunch, an update came in "Twitch" and now when you enter the game - it just hangs. Disable the addon and it works fine, turn it back on - it hangs. Reinstalling the addon does not help, what did the addon do, that it breaks the game? I rolled back the game version in “Twitch” from 05/20/20 3.7.72-classic Release to 05/19/20 3.7.71-classic Release and everything works fine. Please fix the addon while I am on the previous version.

**Comment by sylvanaar** [comment]
New build pushed - sorry about that
