### ISSUE TITLE
[Classic] Nothing can be seen is chat - 100% broken

### ISSUE THREAD

**Issue by Krayde** [sylvanaar/prat-3-0#67]
Chat is completely broken, nothing can be seen. No whispers, not say, yell, trade, LFG - literally nothing! 
Only time i can see the chat is when disabling the addon entirely, which is a big no go (chat unplayable without the addon, especially when you play the AH :)).

I'm playing on **CLASSIC** and here is the swatter error i receive:

Date: 2020-05-20 14:23:04
ID: 2
Error occured in: Global
Count: ∞
Message: ..\AddOns\Prat-3.0\services\chatsections.lua line 609:
   attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Debug:
   [C]: ReplaceIconAndGroupExpressions()
   Prat-3.0\services\chatsections.lua:609: SplitChatMessage()
   Prat-3.0\addon\addon.lua:591:
      Prat-3.0\addon\addon.lua:566
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2792:
      ..\FrameXML\ChatFrame.lua:2785
   (tail call): ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

**Comment by Krayde** [comment]
Fix: Go into the addon in Twitch client, click Versions, download version 3.7.71-classic - DONE!
#thankmelater

**Comment by sylvanaar** [comment]
New Build Pushed sorry

**Comment by PsiloCA** [comment]
u sir need to apologize for nothing. We value your hard word. nobody is perfect etc etc...
