### ISSUE TITLE
After 3.0 update

### ISSUE THREAD

**Issue by raumi21** [sylvanaar/prat-3-0#68]
Date: 2020-05-20 18:10:32
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\services\chatsections.lua line 609:
   attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Debug:
   (tail call): ?
   [C]: ReplaceIconAndGroupExpressions()
   Prat-3.0\services\chatsections.lua:609: SplitChatMessage()
   Prat-3.0\addon\addon.lua:591:
      Prat-3.0\addon\addon.lua:566
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2792:
      ..\FrameXML\ChatFrame.lua:2785
   (tail call): ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30927
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  AskMrRobotClassic, v2
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AtlasLootClassicMaps, vv1.0.0
  buffOmat, v1.82
  CharacterStatsClassic, v3.5.3
  ClassicCastbars, vv1.3.6
  ClassicCastbarsOptions, v
  DBMCore, v1.13.45
  DBMDefaultSkin, v
  DBMSoundEventsPack, v1.6.5
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  G15Buttons, v1.19 (6.0.0)
  HealBot, v1.13.4.9
  HealBotData, v1.13.4.9
  HealBotde, v1.13.4.0
  HealBoten, v1.13.4.9
  HealBotOptions, v1.13.4.9
  HealBotTips, v1.13.4.9
  InFlightLoad, v1.13.005
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.64
  LeatrixPlus, v1.13.64
  MaxCam, vv2.4.2
  NeatPlates, v1.13.4.22
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  NovaWorldBuffs, v1.57
  OmniCC, v8.3.5
  Prat30, v3.7.72
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Spy, v1.0.27
  Stubby, v8.2.6510 (SwimmingSeadragon)
  ThreatClassic2, v2.19
  TitanClassic, v1.2.3.11304
  TitanClassicAmmo, v1.2.3.11304
  TitanClassicBag, v1.2.3.11304
  TitanClassicClock, v1.2.3.11304
  TitanClassicGold, v1.2.3.11304
  TitanClassicLocation, v1.2.3.11304
  TitanClassicLootType, v1.2.3.11304
  TitanClassicPerformance, v1.2.3.11304
  TitanClassicRegen, v1.2.3.11304
  TitanClassicRepair, v1.2.3.11304
  TitanClassicVolume, v1.2.3.11304
  TitanClassicXP, v1.2.3.11304
  TradeSkillMaster, vv4.9.35
  TradeSkillMasterAppHelper, vv4.0.8
  TrinketMenu, v1.13.4.2
  WeakAuras, v2.17.5
  WIM, v3.8.8
  ZPerl, v5.9.5
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v1.13.4.11304 <none>
  (ck=9b9)

**Comment by PsiloCA** [comment]
dealing with a Prat issue as well after recent update. cant see whispers, guild messages, '/s'. I only logged on for the first time today about 20 mins ago but after some trial and error the best i can say right now is that disabling 'Prat' fixed that problem. sorry i dont have more info but it doesnt look like i am the only one experiencing problems.  *also in Classic.

**Comment by PsiloCA** [comment]
386x Prat-3.0-3.7.72-3-gbaa2804\services\chatsections.lua:609: attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Prat-3.0-3.7.72-3-gbaa2804\services\chatsections.lua:609: in function `SplitChatMessage'
Prat-3.0-3.7.72-3-gbaa2804\addon\addon.lua:591: in function <Prat-3.0\addon\addon.lua:566>
(tail call): ?
FrameXML\ChatFrame.lua:2792: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
frame = ChatFrame1 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 isLayoutDirty = false
 tellTimer = 4075.409000
 isDisplayDirty = false
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 checkedGMOTD = true
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 0
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 CanEffectivelyFade = <function> defined =[C]:-1
 print = <function> defined @Prat-3.0\services\print.lua:58
 OnPreSizeChanged = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "General"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:100
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 mouseOutTime = 0
 AcquireFontString = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame1ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 isDocked = 1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Orcish"
 isInitialized = 1
 ScrollByAmount = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = <unnamed> {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 000002430189CAC0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 mouseInTime = 0
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 GetTextColor = <function> defined =[C]:-1
 defaultLanguage = "Orcish"
 ResetAllFadeTimes = <function> defined =[C]:-1
 dbg = <function> defined @Prat-3.0\services\print.lua:62
 GatherSelectedText = <function> defined =[C]:-1
 GetNumVisibleLines = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 0 = <userdata>
 IsSelectingText = <function> defined =[C]:-1
 fadeDurationSecs = 3
 ScrollToBottom = <function> defined =[C]:-1
 ScrollToTop = <function> defined =[C]:-1
 OnFontObject

**Comment by Type-2** [comment]
Date: 2020-05-20 10:42:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\services\chatsections.lua line 609:
   attempt to call field 'ReplaceIconAndGroupExpressions' (a nil value)
Debug:
   [C]: ReplaceIconAndGroupExpressions()
   Prat-3.0\services\chatsections.lua:609: SplitChatMessage()
   Prat-3.0\addon\addon.lua:591:
      Prat-3.0\addon\addon.lua:566
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2792: ChatFrame_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  ClassicCastbars, vv1.3.6
  ClassicCastbarsOptions, v
  ClassPortraitsFinal, v
  DBMCore, v1.13.45
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v8.3.9
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.2.1
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  Informant, v8.2.6508 (SwimmingSeadragon)
  Inventorian, v1.13.2.4-1-g8de6ebb
  Mapster, v1.8.5
  NeatPlates, v1.13.4.22
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  NovaWorldBuffs, v1.57
  NugComboBar, v1.13.4
  NugEnergy, v1.13.17
  Prat30, v3.7.72
  Prat30Libraries, v
  Questie, v5.10.3
  RCLootCouncilClassic, v0.9.1
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic-1-ga64713d
  SortBags, v1.0.0
  SpeedyAutoLoot, v2.0.25
  Stubby, v8.2.6510 (SwimmingSeadragon)
  ThreatClassic2, v2.19
  VendorPrice, v1.3.5
  WeakAuras, v2.17.5
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=826)

**Comment by sylvanaar** [comment]
Yes, My bad. New build has been pushed
