### ISSUE TITLE
Guild achievements and loots do not generate a sound in Sounds.lua

### ISSUE THREAD

**Issue by KyrosKrane** [sylvanaar/prat-3-0#73]
When a guild member gets an achievement or loots a notable item, a message is generated in the "guild" category of messages in the WoW UI. However, this does not generate a sound in Prat when guild sounds are turned on.

My solution has been to add the relevant events to the "guild category" of sounds that Prat uses.

In modules\Sounds.lua, after line 681, add these lines:

```
	if msgtype == "GUILD_ACHIEVEMENT" or msgtype == "GUILD_ITEM_LOOTED" then
		msgtype = "GUILD"
	end

```

**Comment by gizzmo** [comment]
Can we make this an option. Because (IMO) achievements are not as important as someone actually talking.
