### ISSUE TITLE
"Invite" keyword is not made clickable in Battle.net whispers

### ISSUE THREAD

**Issue by KyrosKrane** [sylvanaar/prat-3-0#77]
![image](https://user-images.githubusercontent.com/458727/82747983-e0610800-9d63-11ea-9d74-fde3c2952617.png)

In the pic above, purple is normal in-game whispers. Blue is Battle.net whispers. Notice that the word "invite" is not highlighted as a clickable link in the B.net whisper.

**Comment by sylvanaar** [comment]
That is intentional. Prat doesn't add links in the BNet channel because much of the time the names of battle.net players are obscured from addons.

**Comment by sylvanaar** [comment]
Oh right - we can't make links in BNet chat. So I can't do anything about this
