### ISSUE TITLE
Crash after new update

### ISSUE THREAD

**Issue by Naxterra** [sylvanaar/prat-3-0#78]
Hello

After updating it to 3.0-3.7.80, addons is crashing.

Date: 2020-05-27 10:56:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\addon\locales.lua line 53:
   attempt to index local 'loc' (a nil value)
Debug:
   [string "@Prat-3.0\addon\addon.lua"]:237:
      Prat-3.0\addon\addon.lua:191
   [string "=[C]"]: ?
   [string "@AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua"]:613:
      ...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  AngryAssignments, vv1.13.0c
  BadBoy, vv8.2.5
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  CloseQuestFix, v1.10
  CursorTrail, v8.3.0.3
  DBMArchaeology, v
  DBMCore, v8.3.21
  DBMCountPackHotS, v1.7.7
  DBMCountPackOverwatch, v1.4.11
  DBMDefaultSkin, v
  DBMInterrupts, v8.3.0
  DBMSoundEventsPack, v1.6.5
  DBMStatusBarTimers, v
  DBMVPVEM, v11.0.0
  FishingBuddy, v1.10.8.9
  GatherMate2, v1.45.5
  Grail, v110
  GTFO, v4.55.2
  HandyNotes, vv1.5.10
  HandyNotesArgus, vv0.15
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.33
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.50
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.6.2
  HandyNotesMechagonAndNazjatar, v13
  HandynotesPandaria, v1.4.1
  HandyNotesSuramarShalAranTelemancy, vv1.23
  HandyNotesTimelessIsleChests, v1.22
  HandyNotesUniversalExplorer, v8.3
  HandyNotesVisionsOfNZoth, v38
  HandyNotesWellRead, v8.0.0.0
  LeatrixPlus, v8.3.19
  MasterPlanA, vA
  MBB, v4.0.1
  MikScrollingBattleText, v5.7.150
  MoveAnything, v17.1.0
  NPCScan, v8.0.1.13
  Omen, v3.2.2
  OmniCC, v8.3.5
  Overachiever, v1.0.9
  OverachieverCache, v1.0.9
  Paste, v1.4.10
  Pawn, v2.3.26
  Postal, vv3.6.2
  Prat30, v3.7.80
  Prat30Libraries, v
  Titan, v5.18.7.80300
  TomTom, vv80300-1.1.2
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=618)

Also /pratdebugmsg gives empty result

[10:59:42] empty result
[10:59:42] nil

**Comment by sylvanaar** [comment]
No enUS localizations for the sounds module

**Comment by sylvanaar** [comment]
Seems to not be an issue in 3.7.81. Must have been an issue with the translation system
