### ISSUE TITLE
[UPDATE TO:] Method Dungeon Tools links not working #5

### ISSUE THREAD

**Issue by steel-raven** [sylvanaar/prat-3-0#8]
Hi there. 

So in the new version links send from other players indeed work now without the workaround. 
But if I send a link myself I have the same problem. 
It's not a big deal because I have the route already in my MDT, but it's kinda weird. 

Also "/pratdebugmsg" shows an empty frame now, so I have to post a screenshot. 

![WoWScrnShot_083119_212544](https://user-images.githubusercontent.com/54681027/64068267-12f72d80-cc36-11e9-93d1-904eaf543e5f.jpg)

![WoWScrnShot_083119_204451](https://user-images.githubusercontent.com/54681027/64068226-995f3f80-cc35-11e9-96c2-9d36090fcb31.jpg)

![WoWScrnShot_083119_204816](https://user-images.githubusercontent.com/54681027/64068227-995f3f80-cc35-11e9-8cb6-0159937fafa4.jpg)

**Comment by sylvanaar** [comment]
Oh this is the highlight module

**Comment by sylvanaar** [comment]
Fixed in latest
