### ISSUE TITLE
New Module To Save Blizzard Chat Settings To The User Profile

### ISSUE THREAD

**Issue by sylvanaar** [sylvanaar/prat-3-0#80]
The memory module supports the saving of your game's chat settings to your current Prat profile.

If you use the same profile on each of your characters, this will allow you to have the same chat set-up across your entire account. It is recommended that you use the 'Default' profile on all your characters unless you have more advanced needs.

DEMO: https://streamable.com/as8a6y

The settings that are saved by this module are:

**Frame Appearance and Behavior**

* Frame Name
* Position and Size 
* Minimized state and location
* Background color and opacity
* Font Size
* Statuses: Shown, Docked, Locked and Uninteractable

**Chat Settings**

* Message Types Enabled
* Chat Channels Joined
* Chat Colors
* Chat Tab Flash Behavior
* Chat Related CVars

![Memory - Options Panel](https://content.screencast.com/users/akhtar7512/folders/Snagit/media/97a033e4-0a11-4639-bdc3-8625bf296c09/06.05.2020-01.08.jpg)

**Save Settings** Press this button to save the blizzard chat settings and frame positions to Prat's settings.

**Load Settings** Press this button to load any previously saved settings you have and reconfigure the chatframes based on those settings

**Load Settings Automatically** - Checking this box will load the saved settings automatically on any character that uses the current profile.

**Comment by sylvanaar** [comment]
Will release this as experimental so it can get more testing

**Comment by sylvanaar** [comment]
Going to reopen - maybe I will get some feedback

**Comment by Aur0r4** [comment]
Just tested it in WoW Classic with a Twink. Worked wonderfully as far as I can see right now. Never again adjust the chat windows at Twinks! :)

I like it.

**Comment by MrUzagi** [comment]
I have looked at the module and am liking it so far, but I haven't tested it out much yet.
