### ISSUE TITLE
System messages stop showing up after a while

### ISSUE THREAD

**Issue by themegosh** [sylvanaar/prat-3-0#83]
On classic.

After updating Prat to 3.8.2 today things were working fine for a while, then after a couple hours I stopped seeing system message. Rolls, friends/guildie online/offline, and drunk related messages all stopped appearing, but I was still able to see gold/items/whispers/party/guild/custom channels. I scrolled back through my chat log and wasn't able to identify a swatter message indicating an LUA error, and there is nothing in /swatter show. Not sure how to debug this but others in my guild are having similar issues. If you /reload things work again.

**Comment by sylvanaar** [comment]
Thanks. I see the issue - it is fixed for the next build

**Comment by sylvanaar** [comment]
Oh I have found another issue. Looks like when a temporary chat frame opens the /roll stops working

**Comment by sylvanaar** [comment]
Seems fixed in 3.8.4
