### ISSUE TITLE
Substitutions - Some Don't Work

### ISSUE THREAD

**Issue by orionshock** [sylvanaar/prat-3-0#88]
Many of them don't work in classic

After doing some debug work i have found the fix. 
Move Lines 1753 to 1758 in the modules\Substitutions.lua ( a block that is specific to retail ) to the last entry in the "Prat:SetModulePatterns" call.

It seems like this effective null entry is causing a glitch in the system.

**Comment by sylvanaar** [comment]
Thanks for reporting the issue and the fix!

**Comment by orionshock** [comment]
Correction to my original: 

the block :
`      GetAverageItemLevel and {
        pattern = "(%%ail)",
        matchfunc = PlayerAverageItemLevel,
        optname = PL["PlayerAverageItemLevel"],
        type = "OUTBOUND"
      },`  ( around lines  586-591 ), was turning into a null entry in the table. The behavior was the Substitutions after it were not registered. 

After moving the "PlayerAverageItemLevel" to the end of the table, all of the remaining Substitutions worked as expected. 

Blizzard is using the same API in Retail & Classic for _GetPlayerMapPosition_, and are the ones i wanted to use that started me digging into the code.

**Comment by sylvanaar** [comment]
Hrm, ok.  I will look into adding those back
