### ISSUE TITLE
Errors in other addons probably (!) caused by Prat

### ISSUE THREAD

**Issue by steel-raven** [sylvanaar/prat-3-0#9]
Hi there. 

Since the newest update I experienced an error in two addons (ChampionCommander and Method Dungeon Tools). It's the same error, but of course mentioning the specific files of these addons.
I'm not quite sure of course that it is caused by Prat, but since ChampionCommander and Prat are the only addons that got updates in the last days for me it seems logical. 

Could you please take a look at this GitHub ticket:
https://github.com/alarofrunetotem/ChampionCommander/issues/34

Perhaps you have an idea why this could occur. 

Thanks.

**Comment by sylvanaar** [comment]
No idea - I even looked at his code and couldn't see a connection
