### ISSUE TITLE
Prat 3.0 Prat-3.0-3.8.9-classic.zip -- Message: ..\AddOns\Prat-3.0\modules\Substitutions.lua line 1360:    attempt to index local 'v' (a boolean value)

### ISSUE THREAD

**Issue by emanueol** [sylvanaar/prat-3-0#91]
Date: 2020-06-05 16:59:36
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Prat-3.0\modules\Substitutions.lua line 1360:
   attempt to index local 'v' (a boolean value)
Debug:
   ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144:
      ...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:142
   (tail call): ?
   Prat-3.0\modules\Substitutions.lua:1360: BuildModuleOptions()
   Prat-3.0\modules\Substitutions.lua:1349: OnModuleEnable()
   Prat-3.0\addon\modules.lua:189:
      Prat-3.0\addon\modules.lua:178
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:380: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:695:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  KalielsTracker, v0.3.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AmaluSoundpack, v2.0.3beta - Classic
  AmaluSoundpackplus, v2.1.0beta
  Armory, vv1.7.0
  AskMrRobotClassic, v2
  Atlas, vv1.47.00.11303.00
  AtlasBattlegrounds, vv1.46.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasTransportation, vv1.46.03.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.64
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BuffwatchClassic, v1.14
  CharacterNotes, v8.2.7
  CharacterStatsClassic, v3.5.3
  ClassicBlacklist, v1.1.7
  ClassTrainerPlus, v0.7-beta
  Clique, vv1.0.3-classic
  CoolLevelUp, v1.13.0.2
  DBMCore, v1.13.47
  DBMCountPackOverwatch, v1.4.11
  DBMDefaultSkin, v
  DBMSoundEventsPack, v1.6.5
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  DejaClassicStats, v1304r002
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Ellipsis, v1.0
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  Examiner, vClassic Fan Update (1.09.2)
  ExRT, v4150
  FiveSecondRule, v1.21
  FleecingTip, v113.1672(060320)
  GatherMate2, v1.45.5
  GatherMate2MapButton, v1.1
  GatherNotify, v1.6
  GatherSage2, v20191226
  GatherTrackingReminder, v1.0
  GlobalIgnoreList, v1.13.3
  Grail, v110
  Grid2, vr955
  Grid2LDB, vr955
  Grid2RaidDebuffs, vr955
  GroupCalendar, v
  GuildRosterManager, v1.88
  GuildSearch, v8.2.1
  GuildTooltip, v2.13.13
  ItemAutocomplete, v1.0.6
  ItemRack, v
  ItemTooltipProfessionIcons, v1.1.6
  KiwiItemInfo, vv2.3.4
  LeatrixMaps, v1.13.66
  LibClassicDurations, v1.56
  MaxCam, vv2.4.2
  NovaWorldBuffs, v1.60
  NugRunning, v1.13.38
  OmniCC, v8.3.5
  OPie, vAncient Walnut 6
  PallyPower, vv1.1q-classic
  Pawn, v2.3.28
  Prat30, v3.8.9
  Prat30Libraries, v
  Puggle, v2.9
  PugLoot, vv1.1.1
  Quartz, v3.5-classic-5
  QuestAnnounce, v8.0.2.1
  QuestGuru, v2.1.7
  Questie, v5.10.3
  RCLootCouncilClassic, v0.10.1
  Recap, v5.07
  RecipeRadarClassic, v1.0.0.23
  RollTrackerClassic, v2.21
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic-1-ga64713d
  SimpleDing, vv1.1.1
  SimpleItemLevel, v1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  StatPriorityTracker, v0.0.3b
  Storyline, v1.13.2.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalentSequence, v2.0
  ThreatClassic2, v2.19
  TidyPlatesThreatPlates, v1.3.1
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.2.3.11304
  TitanClassicAmmo, v1.2.3.11304
  TitanClassicBag, v1.2.3.11304
  TitanClassicClock, v1.2.3.11304
  TitanClassicGold, v1.2.3.11304
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.2.3.11304
  TitanClassicLootType, v1.2.3.11304
  TitanClassicPerformance, v1.2.3.11304
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRegen, v1.2.3.11304
  TitanClassicRepair, v1.2.3.11304
  TitanClassicRestPlus, v1.0.0.1
  TitanClassicVolume, v1.2.3.11304
  TitanClassicXP, v1.2.3.11304
  TitanProfession, vv1.3-classic
  TitanProfessionsMulti, v1.5.1
  TitanSkills, v1.7.0
  TitanSocial, v1.13.3
  TomTom, vv11304-1.1.2
  TownsfolkTracker, v1.0.7
  VendorPrice, v1.3.5
  WeakAuras, v2.17.5
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.7
  WhereToGatherClassic, v1.0
  Wholly, v079
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=ee0)

**Comment by sylvanaar** [comment]
Fixed in the next build
