### ISSUE TITLE
[WoW Classic] Tabs loose selected channels on UI reload

### ISSUE THREAD

**Issue by Licen-it** [sylvanaar/prat-3-0#93]
It happens every time i open the game or reload UI that the tabs i have don't have any channel selected but for a few of them. The most frustrating is the default `General tab` that only selects `Trade` channel, but every time i login i have to manually select `General` channel, `local defence` and `looking for group`. I tried hitting the reset button on the addon settings but it didn't fix the issue. Any other idea?

**Comment by sylvanaar** [comment]
Are you using the Memory module?

**Comment by Licen-it** [comment]
yes

**Comment by Licen-it** [comment]
I just noticed that in Stormwind it keeps `General` and the other channel selected in the `General tab`, while the custom tab gets cleared from channels. When i opened the issue i was in Ironforge, but when i noticed it the first time i didn't think that changing the region might alter the behaviour.

**Comment by sylvanaar** [comment]
Hmm. Ok that is really good to know. Memory module has gotten a lot of fixes today. Though I didn't know about joining in different capitals. I will take a look!

**Comment by sylvanaar** [comment]
I think I might see one issue.

hey when you type /2  does it work? Is the issue that it just doesn't appear in the window?

**Comment by sylvanaar** [comment]
Will you try this build to see if there is any improvement

https://www.wowace.com/projects/prat-3-0/files/2976722

**Comment by Licen-it** [comment]
Yes if i type /1 or /2 it works...but the message is not displayed because the tab loose the setting to display that channel...i'll try that later today and let you know
