### ISSUE TITLE
Messages in saved history are not fading correctly

### ISSUE THREAD

**Issue by KyrosKrane** [sylvanaar/prat-3-0#98]
Fading of old messages with chat history turned on is inconsistent. This is with Prat v 3.8.20.

I logged in and AFK'ed. When I noticed a new message, I looked at my chat window and saw this:
![image](https://user-images.githubusercontent.com/458727/84440240-41f7f200-abff-11ea-94f1-97faaeba18f1.png)

After a while, it fades to this:
![image](https://user-images.githubusercontent.com/458727/84440275-4c19f080-abff-11ea-8932-6f0aebac043a.png)

By scrolling down to refresh the chat, it looks like this.
![image](https://user-images.githubusercontent.com/458727/84440302-5936df80-abff-11ea-8db9-df18e24868ac.png)

Essentially it seems that messages saved in history are not being faded out any more at the timeout. 

Possibly related issue, the time since last login appears to have changed too - it's showing negative seconds, among other oddities.

**Comment by sylvanaar** [comment]
Yes - that negative time would be related in a big way. If the time for those lines is in the future - they will never fade.

Now I wonder how they got that way. Can you grab some examples of entire message structure for a few of the chat lines from your saved variables

**Comment by KyrosKrane** [comment]
I found the SavedVariables for that character, and edited the file to only keep the sections for ChatFrame3 (the one displayed in those screeshots) for privacy. I didn't remove anything within the ChatFrame3 sections. I've attached the file. If you need my full saved variables file, I can provide that to you directly - either email to you, or you can provide me your GPG public key and I can encrypt and upload it here.

[CF3.txt](https://github.com/sylvanaar/prat-3-0/files/4768120/CF3.txt)

**Comment by KyrosKrane** [comment]
I'm seeing this on other characters with more active chats as well; the same fading issue is happening for them. If you need those, I can provide the full saved variables again directly or encrypted here.

**Comment by sylvanaar** [comment]
Oh right I see. This was a huge oversight when I moved to use the blizzard internal chatframe buffer instead of keeping my own.

**Comment by KyrosKrane** [comment]
Retested on v3.8.21. Seems fixed, and working the way it used to before. Thanks!

**Comment by sylvanaar** [comment]
> Retested on v3.8.21. Seems fixed, and working the way it used to before. Thanks!

Great!
